### ISSUE TITLE
any way I can increase the disk storage on MPC temporarily

### ISSUE THREAD

**Issue by suredream** [microsoft/PlanetaryComputer#107]
Hi:

I can see for the CPU instance I have on MPC, It comes with 43G memory but only 14G diskspace.

The memory is good but disk space is too limited. Any way I can increase it for regular job?

Many thanks,

**Comment by TomAugspurger** [comment]
The [filesystem](https://planetarycomputer.microsoft.com/docs/overview/environment/#understanding-the-file-system) section of our docs touches on this I think. On the Hub, the (15G) home directory should really just be used for code / small outputs.

Use `/tmp` for caching files temporarily to a local disk. That's cleared between notebook sessions.

To persist large files between notebook sessions, the best option is Azure Blob Storage in your own subscription. https://planetarycomputer.microsoft.com/docs/quickstarts/storage/ has a short example.

**Comment by suredream** [comment]
Tks, Tom.  

`That's cleared between notebook sessions.` How long a MPC session will be stopped automatically?

**Comment by TomAugspurger** [comment]
I believe it's daily or after about 30 minutes of inactivity.

Tom
________________________________

**Comment by TomAugspurger** [comment]
Closing, but LMK if you have any outstanding questions.
