### ISSUE TITLE
Authentication Error: When trying to write the data more than 5 yrs into netcdf file

### ISSUE THREAD

**Issue by devosse1** [microsoft/PlanetaryComputer#109]
Downscale version: Conventions: CF-1.7 CMIP-6.2
    activity_id: ScenarioMIP
    contact: [climatesci@rhg.com](mailto:climatesci@rhg.com)
    data_specs_version: 01.00.30
    Python version: Python 3.9
    Operating System: Ubuntu

Description

ClientAuthenticationError: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed

Ran into a deserialization error. Ignoring since this is failsafe deserialization
Traceback (most recent call last):
File "/home/user/my_project_dir/anaconda3/lib/python3.9/site-packages/msrest/serialization.py", line 1509, in failsafe_deserialize
________
What I Did:
________
I am calculating month Tamax mean and then writing it into netcdff file as I need the downscale data to be fed as input in a model
subset = all_datasets.sel(lon=slice(25, 45),lat=slice(-10, 10),)
mtasmax = subset.resample(time="M").mean()
delayed_obj = mtasmax.sel( time=slice("2025-01-01", "2030-12-31")).to_netcdf('rgrp_yr2_2025_2030.nc',compute=False)

I am also using the temporary url (I think?) because in the documentation it was written that for this dataset tokens not need also the url should be "A SAS token is needed whenever you want to access Planetary Computer data at an Azure Blob URL. For example, an Azure Blob URL looks like:

https://landsateuwest.blob.core.windows.net/landsat-c2/level-2/standard/oli-tirs/2021/141/045/LC08_L2SP_141045_20210329_20210402_02_T1/LC08_L2SP_141045_20210329_20210402_02_T1_SR_B1.TIF "
________
this is what I am using:
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1/",
    modifier=planetary_computer.sign_inplace,
)

if I run for 10 years or 5 years or if the notebook is running for quite some time it shows this Client authentication error

can some please in regards to this?
![image](https://user-images.githubusercontent.com/60099425/192468968-495ed1b6-8b6b-40ad-a482-cfdc83b341dd.png)

**Comment by TomAugspurger** [comment]
Do you have a full reproducible example I can try out to reproduce this? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

A couple of questions to get started:

1. Can you check the expiry component of the SAS token (I think it's the datetime after the "se" parameter), and compare it to the datetime your exception is raised?
2. Do you still see the error if you use [supply a subscription key](https://planetarycomputer.microsoft.com/docs/concepts/sas/#supplying-a-subscription-key) when you get the SAS token / sign the STAC items?

**Comment by devosse1** [comment]
the code -
``` 
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1/",
    modifier=planetary_computer.sign_inplace,
)


search = catalog.search(
    collections=["cil-gdpcir-cc0", "cil-gdpcir-cc-by"],
    query={"cmip6:experiment_id": {"eq": "ssp370"}
          },
)
ensemble = search.get_all_items()
len(ensemble)

import collections
collections.Counter(x.collection_id for x in ensemble)

##select this variable ID for all models in a collection
variable_id = "pr"

datasets_by_model = []

for item in tqdm(ensemble):
    asset = item.assets[variable_id]
    datasets_by_model.append(
        xr.open_dataset(asset.href, **asset.extra_fields["xarray:open_kwargs"])
    )

all_datasets = xr.concat(
    datasets_by_model,
    dim=pd.Index([ds.attrs["source_id"] for ds in datasets_by_model], name="model"),
    combine_attrs="drop_conflicts",
)




for i in range(2033,2040):
    yearprefix='-01-01'
    yearsuffix='-12-31'
    year_b=str(i)+yearprefix
    year_e=str(i)+yearsuffix
    y_subset = all_datasets.sel(lon=slice(25, 45),lat=slice(-10, 10),time=slice(year_b, year_e))
    print(year_b,year_e)
    with ProgressBar():
            temp = y_subset.compute()
            temp.resample(time='M').mean().to_netcdf('pr'+'_'+'ssp370'+str(i)+'.nc',compute=False)
```
1) I don't think I am using a SAS token , I am using the methodology mentioned in the  https://planetarycomputer.microsoft.com/dataset/cil-gdpcir-cc-by#Ensemble-example.

**Comment by devosse1** [comment]
^^update 
I was able to workaround it , if I run my notebook in the planetary computer hub, it gets downloaded without any error and at ease.
but these errors are there if I run the notebook in my local machine even after providing the key for the same planetary computer.

**Comment by TomAugspurger** [comment]
Thanks for following up. I was testing it out and it ran without problem on the Planetary Computer Hub for the full set of years.

The only thing special about the hub is that it automatically sets your `PC_SDK_SUBSCRIPTION_KEY` environment variable so that you get the longer-lived SAS tokens. It is important to note that placing your compute in the West Europe Azure region (where the data is stored) will really speed up the computation.

Finally, the most recent release of xarray had some really big speedups for this kind of operation.

```python
subset = all_datasets.sel(lon=slice(25, 45),lat=slice(-10, 10))
out = subset.resample(time="M").mean()
out.to_zarr("/tmp/out.zarr", mode="w")
```

took about 30 minutes. That could be parallelized on a cluster if you were to write to Azure Blob Storage.

**Comment by devosse1** [comment]
As I mentioned in Planetary Computer Hub, it worked fine, I too was able to download.
But in local machine even after providing the SUBSCRIPTION_KEY in the API request, it runs into deserialization errors as provided in the screengrabs which is not at all pleasant.
In the documentation it was mentioned, Rate limiting and token expiry are dependent on two aspects of each requests:

    Whether or not the request is originating from within the same data center as the Planetary Computer service (West Europe)

    Whether or not a valid API subscription key has been supplied on the request

even if 2nd  is also true, the running of code really drags down to painfully slow.

But thanks for the tip and prompt response :)

**Comment by TomAugspurger** [comment]
> even if 2nd is also true, the running of code really drags down to painfully slow.

Do you know the cause of the slowness? I suspect the bottleneck is network bandwidth being slower going from Azure -> public internet than within the same datacenter.

**Comment by devosse1** [comment]
I don't think so , I am using my campus intranet which has pretty highspeed. I think its something with the API pipeline but you might be also correct regarding switching data centers. But I read for trying to fix the deserialization errors, it was in regards to pystac call. Also even with the Subscription key, the notebook couldnot run beyond 5 years without going through errors, some rate limiting threshold(?!)  But maybe you can try in your local computer ?

**Comment by TomAugspurger** [comment]
> the notebook couldnot run beyond 5 years without going through errors, some rate limiting threshold(?!)

The only rate limiting is on calls to the SAS API, which you only do once, so I don't think it's that.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.

Note that download speeds from Azure are determined not just by your ISP but also by the speed of the blob service.
