### ISSUE TITLE
Availability of opencv in HUB

### ISSUE THREAD

**Issue by 007anupamdas** [microsoft/PlanetaryComputer#115]
I found that opencv package (cv2) is not available by default at the HUB. It is very important package, that has image handling, preprocessing, machine learning etc. capabilities.

**Comment by rasyidstat** [comment]
It would be very great if cv2 could be added because this package is widely used for image processing
I was trying to install cv2 in the hub but it failed because of missing dependencies

**Comment by 007anupamdas** [comment]
I agree with @rasyidstat. There are specific functions which are only available in opencv, which we use exhaustively in our work. Scikit doesn't heed to my needs. I was able to install opencv, after working around with the dependencies, which are tough to install. But I had to install everytime I launch the server. 
Opencv is much more famous than rioxarray and widely used in image processing domain, and yet I was surprised it was not included by default.

**Comment by Proghead231** [comment]
@007anupamdas  Hey, can you please tell me what worked for you? I was able to install opencv, but every time I try to import it or use any other packages dependent on it, I am getting the following error.

 ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 import cv2

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by masiddique** [comment]
@007anupamdas I have the same request as from @Proghead231 
I cannot find a work around the missing opencv.

**Comment by ghidalgo3** [comment]
The hub is no longer available.
