### ISSUE TITLE
Should Sentinel-2 STAC Collection declare EO extension?

### ISSUE THREAD

**Issue by kylebarron** [microsoft/PlanetaryComputer#116]
Should the Sentinel 2 collection declare the eo extension as well? Right now it puts `eo:bands` on `item_assets` but the top-level `stac_extensions` array doesn't declare the EO extension. https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a

@TomAugspurger pointed out https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#stac_extensions, which says

> This must not declare the extensions that are only implemented in child Collection objects or child Item objects.

But I'd counter by pointing out that the [EO extension spec's json schema](https://github.com/stac-extensions/eo/blob/d302b29262f2769c2579ebcac9caa336e75352f5/json-schema/schema.json#L91-L96) also applies to a collection's `item_assets`. Therefore, I'd think that since the Sentinel 2 Collection file defines `eo:bands` on `item_assets`, the extension should be declared.

**Comment by TomAugspurger** [comment]
Worth mentioning that we do include `eo` in collections like https://planetarycomputer.microsoft.com/api/stac/v1/collections/modis-09A1-061 and https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
