### ISSUE TITLE
Missing Granules in the MOD11A2 Product

### ISSUE THREAD

**Issue by BnJam** [microsoft/PlanetaryComputer#150]
Below, is the data coverage over Canada and clearly missing a granule after querying PC STAC (left) with the same bounding box as used on the EarthData (right). In some date ranges, the number of returned granules is around 8 or 9 - whereas using EarthData gives a consistent 14 granules at any temporally ranged period for this AOI. 

```python
bounding_box = [-102.041016,41.836828,-50.493200,62.794935]
polygon = shapely.geometry.box(*bounding_box, ccw=True) 
polygon = gpd.GeoDataFrame(index=[0], crs='EPSG:4326', geometry=[polygon])
footprint = polygon.to_crs('epsg:4326').geometry[0].envelope
date_range = '2001-01-01/2001-12-30'

items = api.search( 
    collections = ['modis-11A2-061'], 
    intersects = footprint, 
    query={"eo:cloud_cover": {"lt": MAX_CLOUD}}, 
    datetime = date_range, 
).get_all_items()
```

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/16641658/207113269-70b4fb05-9586-4fe0-9fd4-97c85e722310.png)

**Comment by TomAugspurger** [comment]
Thanks for the report. I'll take a closer look later, but cross-linking to https://github.com/microsoft/PlanetaryComputer/discussions/136 which reports a similar issue for `modis-11A1-061`.

**Comment by TomAugspurger** [comment]
@BnJam https://github.com/microsoft/PlanetaryComputer/discussions/136 is fixed now, so I suspect that if you rerun this you'll get the results you expect. Let me know if not and I'll reopen this.
