### ISSUE TITLE
Date selection bug in Explore datepicker UI

### ISSUE THREAD

**Issue by ChristopheKar** [microsoft/PlanetaryComputer#162]
When using the datepicker in the custom filter for data acquisition dates, there seems to be a bug in the datepicker's UI. When I select a date by clicking on a day, the day before is selected. For example, if I click on June 16, I get June 15 selected instead. In the image below, if I click on the first "29" that appears (effectively May 29), nothing happens, and going back a month reveals that May 28 was in fact selected.

This does not seem to be related to a specific dataset, as I have had it happen with multiple datasets.

![image](https://user-images.githubusercontent.com/40264902/211887289-7075f348-7b49-4c0e-a124-dba3aeed7109.png)

URL to reproduce: https://planetarycomputer.microsoft.com/explore?c=-4.4614%2C46.6354&z=5.94&v=2&d=landsat-c2-l2&s=false%3A%3A100%3A%3Atrue&ae=0&sr=desc&m=cql%3A8a04719e4e045ecff772d47fcc6ad348&r=Natural+color

**Comment by mmcfarland** [comment]
Hi @christophekar, thanks for the report and repro instructions. I wasn't able to immediately reproduce this issue, can you share what browser and OS you are using?

And to clarify, when you click on a date the previous date is both visually selected and actually used in the custom date range?

**Comment by ChristopheKar** [comment]
Sorry about that, I am using Linux, and I was able to get this behavior on both Chromium and Firefox:
- Chromium: Version 108.0.5359.124 (Official Build) Arch Linux (64-bit)
- Firefox: Version 108.0.2 (64-bit) 

And yes, the previous date is both visually selected in the datepicker and in the custom date range.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
