### ISSUE TITLE
National Wetlands Inventory example notebook not working

### ISSUE THREAD

**Issue by giswqs** [microsoft/PlanetaryComputer#174]
Excited to see the newly added National Wetlands Inventory. I just tested the example notebook and got the following error.
https://planetarycomputer.microsoft.com/dataset/fws-nwi

```python
item = collection.get_item("DC")
```
> HTTPError: 404 Client Error: Not Found for url: https://planetarycomputer.microsoft.com/api/sas/v1/token/landcoverdata/fws-nwi-onboarding

**Comment by TomAugspurger** [comment]
Thanks for the report. This should be fixed now, and apologies for the error.

There was a typo in one of our configuration tables so this storage container set up properly. And our regular integration tests didn't catch it unfortunately.
