### ISSUE TITLE
Update R environment 

### ISSUE THREAD

**Issue by gilbertocamara** [microsoft/PlanetaryComputer#181]
Dear @TomAugspurger, would it be possible to update the R environment for the latest version, as follows:

(a)  R: at least version 4.1., if possible 4.2.2
(b) sits: version 1.2
(c) Other packages
    dplyr (>= 1.0.0),
    gdalcubes (>= 0.6.0),
    luz (>= 0.3.0),
    parallel (>= 4.0.5),
    purrr (>= 0.3.0),
    rstac (>= 0.9.1-5),
    sf (>= 1.0),
    slider (>= 0.2.0),
    stars (>= 0.6),
    terra (>= 1.6),
    testthat (>= 3.1.3),
    tibble (>= 3.1),
    tidyr (>= 1.2.0),
    tmap (>= 3.3),
    torch (>= 0.9.0),
    torchopt(>= 0.1.2)

Many thanks!!

**Comment by TomAugspurger** [comment]
Thanks Gilberto. I've updated the R environment to the versions at https://github.com/microsoft/planetary-computer-containers/blob/main/r/conda-linux-64.lock. Specifically,

- R=4.2.2
- sits=1.2.0
- torch=0.9.0

let me know if you spot any issues.

**Comment by gilbertocamara** [comment]
Dear Tom Great! Many thanks. We tested and everything works.Best Gilberto Sent from my iPhoneOn 6 Feb 2023, at 17:15, Tom Augspurger ***@***.***> wrote:﻿
Thanks Gilberto. I've updated the R environment to the versions at https://github.com/microsoft/planetary-computer-containers/blob/main/r/conda-linux-64.lock. Specifically,

R=4.2.2
sits=1.2.0
torch=0.9.0

let me know if you spot any issues.

**Comment by TomAugspurger** [comment]
Closing this as completed.
