### ISSUE TITLE
How to ingest my own data layers through MPC's, or I have to build my own stac service and make it accessible by MPC?

### ISSUE THREAD

**Issue by suredream** [microsoft/PlanetaryComputer#20]

**Comment by suredream** [comment]
Thanks Tom.  If I have a lot of COG which already has been put into COG on AWS S3, is it possible to make it accessible to pystac without copying to azure blob?

**Comment by TomAugspurger** [comment]
It is possible, yes, but depending on the workload I might not recommend it.

The actual library loading the data (probably GDAL) is able to read from S3 as long as you have the right permissions / credentials. That said, you might not want to move large amounts of data out of AWS over the public internet. Cloud providers (including AWS and Azure) typically charge egress fees when data leave the cloud's region. And it will be much slower than accessing the data from the same cloud region.

So for even moderately sized datasets, I would recommend putting your compute and data in the same region.

And just to clarify one thing: STAC is just a metadata standard. So your STAC items can live anywhere (Azure Blob Storage, S3, a local hard drive, etc.). The STAC items include assets which are links to the actual data (COG files in your case). So pytsac can read from anywhere too.

**Comment by suredream** [comment]
1. I can create STAC metadata (.json) everything for pystac to discovery.
2. The COG data will be COG either on S3 or Azure with credentials.
3. So, if I run pc on an aws instance which is located in the same region with my S3 data, that would be the equivalent with the accessing azure blob using pc instance, am I right?

**Comment by TomAugspurger** [comment]
Yep, that sounds about right.

**Comment by suredream** [comment]
Many thanks! Tom
