### ISSUE TITLE
Unable to open Pytorch / Tensorflow on the Hub - Planetary Computer

### ISSUE THREAD

**Issue by Flarisca** [microsoft/PlanetaryComputer#202]
Hi,

I'm trying to use Pytorch / Tensorflow on the Hub - Planetary Computer. It took a long time to start up before returning this issue:

<img width="1440" alt="Screenshot 2023-03-23 at 23 10 37" src="https://user-images.githubusercontent.com/90389779/227265738-39902439-7bd2-415d-8209-95e895c75950.png">

I've tried to look up on solutions, but found nothing. What should I do?

**Comment by TomAugspurger** [comment]
The Hub does have a maximum number of GPU nodes available for all users. Most likely, you're hitting that cap.

You might try using the CPU environment, or deploy some compute in your own Azure subscription. [This page](https://planetarycomputer.microsoft.com/docs/concepts/computing/) has some information.

**Comment by Flarisca** [comment]
Hi,

Thank you for your suggestion. I've decided to use GitHub and I'm able to
use Planetary on GitHub now. However, using Pytorch requires some
configurations that I'm unfamiliar with. Is there any guideline on how to
specifically set up Pytorch there?

Thank you,

**Comment by TomAugspurger** [comment]
The [pytorch docs](https://pytorch.org/)  and this [Azure page](https://azure.microsoft.com/en-us/resources/developers/pytorch/) might be helpful.

**Comment by ghidalgo3** [comment]
The hub is no longer available.
