### ISSUE TITLE
Inconsistent Sentinel-2 L2A Raster Footprint Polygons

### ISSUE THREAD

**Issue by scottyhq** [microsoft/PlanetaryComputer#220]
It seems like some STAC Items for Sentinel-2 L2A Use the MGRS Square as the STAC geometry and others use a valid data footprint. Maybe the metadata generation changed at some point in time? 

<img width="1112" alt="Screenshot 2023-05-22 at 10 15 44 AM" src="https://github.com/microsoft/PlanetaryComputer/assets/3924836/65618163-beae-497f-a71e-b0c73172b7d9">

https://planetarycomputer.microsoft.com/api/data/v1/item/map?collection=sentinel-2-l2a&item=S2A_MSIL2A_20151228T050222_R119_T45RVM_20210526T203938

https://planetarycomputer.microsoft.com/api/data/v1/item/map?collection=sentinel-2-l2a&item=S2B_MSIL2A_20230505T045659_R119_T45RVM_20230505T104315

The stactools library suggests using a valid data footprint
https://stactools.readthedocs.io/en/stable/api.html#module-stactools.core.utils.raster_footprint

**Comment by ZirconCode** [comment]
I've also run into this, but I've found correct polygons before and after a broken one, so haven't been able to pin it down.

**Comment by TomAugspurger** [comment]
I think that the version of https://github.com/stactools-packages/sentinel2 just gets the geometry from the metadata provided by ESA. It'd be good to confirm that first.

We do have the option to generate geometries from the actual rasters themselves, using the `raster_footprint` utility. That said, I am a bit worried about the computation cost of doing that for a dataset of sentinel-2's size.

**Comment by cmosig** [comment]
Is there any update on this?  

I just posted [this](https://github.com/microsoft/PlanetaryComputerDataCatalog/issues/448) but then found this repo later.

**Comment by TomAugspurger** [comment]
No updates from me. Might be worth reaching out to ESA to report the issue, in case they're able to fix it at the source.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
