### ISSUE TITLE
Not able to connect with VSCODE

### ISSUE THREAD

**Issue by cordmaur** [microsoft/PlanetaryComputer#23]
HI,
I've been using Planetary HUB, but I'm struggling to connect to the HUB server through VSCODE, as instructed in: https://planetarycomputer.microsoft.com/docs/overview/ui-vscode/

I have started the server, created a specific Token and used the following URL on VSCODE:
![image](https://user-images.githubusercontent.com/19617404/150205019-10abc2a0-50bd-4ecb-98a0-259cae96c56b.png)

After Reloading VSCode as demanded, when I try to run a simple (2+2) cell, it asks for a "kernel".
![image](https://user-images.githubusercontent.com/19617404/150205246-8a246a32-4974-4f84-8a57-5e91ce628b4a.png)

Everything seems right... I connect to another existing (remote) jupyter server to test my local configuration (VSCODE and extension) and it worked flawlessly.

Thanks

**Comment by TomAugspurger** [comment]
There was another report of this in https://github.com/microsoft/planetary-computer-hub/issues/45. I've been able to reproduce it, but not reliably, and haven't been able to figure out exactly where things are breaking down :/

**Comment by TomAugspurger** [comment]
Closing this in favor for https://github.com/microsoft/planetary-computer-hub/issues/45 to consolidate things.

I'll note that I was able to log in successfully when I just tried to debug this again. So it's seemingly inconsistent.
