### ISSUE TITLE
S1 signing 403 error

### ISSUE THREAD

**Issue by ZirconCode** [microsoft/PlanetaryComputer#230]
I'm trying to retrieve some S1 `sentinel-1-rtc` imagery, `IW` with polarizations `VV, VH`.

A standard catalog search:
```
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1") 
search = catalog.search(
  collections=["sentinel-1-rtc"],
  intersects=AoI,
  datetime=[date]
)
search_result = search.items()
items = list(search_result)
```

Signing:
`signed_items = [pc.sign(item).to_dict() for item in items]`
Gives me an: `HTTPError: 403 Client Error: Forbidden for url: https://planetarycomputer.microsoft.com/api/sas/v1/token/sentinel1euwestrtc/sentinel1-grd-rtc` error.

I'm running the code locally to debug, but have the `PC_SDK_SUBSCRIPTION_KEY` env variable set. This has always worked for S2, but not for S1.

Using currently `planetary-computer==0.4.9`.

**Comment by TomAugspurger** [comment]
The only thing special about sentinel-1-rtc is that it *requires* an account key. Can you double check that your key is getting picked up properly:

```
In [1]: import planetary_computer

In [2]: assert planetary_computer.settings.Settings().subscription_key
```

That should print out nothing. If it raises an error then your key isn't set. Maybe check the environment variable?

If it is set, then maybe double check that they key is correct by re-copying it from https://planetarycomputer.developer.azure-api.net/

**Comment by ZirconCode** [comment]
Thank you for the always incredibly fast and spot-on support!

It works now, the issue was indeed a missing key due to a weird import/env timing issue in my local setup.
