### ISSUE TITLE
STAC item expression not working 

### ISSUE THREAD

**Issue by giswqs** [microsoft/PlanetaryComputer#234]
The tile URL returned from the PC STAC API stops working if there is an expression in it, such as `{expression': '(SR_B5-SR_B4)/(SR_B5+SR_B4)}'` for calculating NDVI. Here is an example that can reproduce this issue. It used to be able to display both the Landsat image and NDVI image, but now the NDVI image is blank. Any advice? @TomAugspurger @vincentsarago

Relevant issue: https://github.com/opengeos/leafmap/issues/448

```python
import requests
import leafmap
url = 'https://planetarycomputer.microsoft.com/api/data/v1/item/WebMercatorQuad/tilejson.json'
kwargs = {'collection': 'landsat-8-c2-l2', 'item': 'LC08_L2SP_047027_20201204_02_T1', 'assets': ['SR_B5', 'SR_B4', 'SR_B3'], 'rescale': '7144.0,22265.0'}
kwargs2 = {'expression': '(SR_B5-SR_B4)/(SR_B5+SR_B4)', 'rescale': '-1,1', 'colormap_name': 'greens', 'collection': 'landsat-8-c2-l2', 'item': 'LC08_L2SP_047027_20201204_02_T1'}
r = requests.get(url, params=kwargs).json()
r
r2 = requests.get(url, params=kwargs2).json()
r2
m = leafmap.Map()
m.add_tile_layer(url=r['tiles'][0], name='landsat', attribution='PC') # working
m.add_tile_layer(url=r2['tiles'][0], name='ndvi', attribution='PC')  # not working
m
```

**Comment by vincentsarago** [comment]
@giswqs you need to add `asset_as_band=True`

**Comment by giswqs** [comment]
@vincentsarago Thank you for the tips. It works now. It seems `asset_as_band` is a new option added a few months ago.

https://github.com/developmentseed/titiler/pull/550

**Comment by TomAugspurger** [comment]
Thanks Vincent!
