### ISSUE TITLE
Incorrect proj:transform in some 3DEP Seamless DEM items

### ISSUE THREAD

**Issue by hrodmn** [microsoft/PlanetaryComputer#241]
I discovered a problem with the `proj:transform` values in at least some of the 3DEP Seamless DEM STAC items today! I use `stackstac` to load data and came across a situation where several items unambiguously overlap an area of interest but the arrays come back empty. After some sleuthing I realized that the pixel height/width values in `proj:transform` were an order of magnitude too small!

Here is a reprex that demonstrates that the bounds you get from `proj:shape` and `proj:transform` do not match the expectation for a few items:
```python
import affine
import planetary_computer
import pystac_client
import rasterio.transform


bbox = (-122.406, 36.215, -121.467, 36.743)

catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)

search = catalog.search(
    collections="3dep-seamless", bbox=bbox
)

items = search.item_collection()

for item in items:
    bbox_transform = rasterio.transform.array_bounds(
        height=item.properties["proj:shape"][0],
        width=item.properties["proj:shape"][1],
        transform=affine.Affine(*item.properties["proj:transform"])
    )
    print(item.id)
    print("\n")
    print("item bbox")
    print(item.bbox)
    print("\n")
    print("proj:transform")
    print(item.properties["proj:transform"])
    print("\n")
    print("bbox from proj:transform and shape")
    print(bbox_transform)
    print("\n\n")
```

Here is the summary from one of the items:
```
n37w122-13

item bbox
[-122.0005555556, 35.99944444444, -120.9994444445, 37.00055555556]

proj:transform
[1e-05, 0.0, -122.0005555556, 0.0, -1e-05, 37.00055555556, 0.0, 0.0, 1.0]

bbox from proj:transform and shape
(-122.0005555556, 36.89243555556, -121.8924355556, 37.00055555556)

```

I only discovered this after inspecting the raw file with `gdalinfo`, but here is an example that uses `rasterio` to show the problem:
```python
import rasterio
with rasterio.open(items[2].assets["data"].href) as src:
    transform = src.transform
print(transform)
```
```
Affine(9.259259259300006e-05, 0.0, -122.00055555555556,
       0.0, -9.259259259300006e-05, 37.00055555555556)
```

The STAC item metadata disagrees:
```python
affine.Affine(*items[2].properties["proj:transform"])
```
```
Affine(1e-05, 0.0, -122.0005555556,
       0.0, -1e-05, 37.00055555556)
```

**Comment by TomAugspurger** [comment]
Thanks for the report. This sounds somewhat similar to https://github.com/microsoft/PlanetaryComputer/issues/126. Do they sound the same to you?

I'll post a status update over there.

**Comment by hrodmn** [comment]
@TomAugspurger - yep my issue looks redundant with #126. It sounds like you've got a fix in place in the stactools.threedep!
