### ISSUE TITLE
Is the era5 data only available until 2020? 

### ISSUE THREAD

**Issue by xiangyi-wang** [microsoft/PlanetaryComputer#244]
The data description is updated to present，but in reality, data is only available until 2020
![image](https://github.com/microsoft/PlanetaryComputer/assets/22881957/d3987814-9e75-4a37-92f4-555c50372b1f)

**Comment by TomAugspurger** [comment]
See https://github.com/microsoft/PlanetaryComputer/discussions/242#discussioncomment-6542745 for an update.

tl/dr: we might need to shift to a new collection to avoid breaking backwards compatibility. When that's up and running I'll update the endpoint on this `era5-pds` collection.
