### ISSUE TITLE
missing Sentinel-2 L2a data since 29th July 2023

### ISSUE THREAD

**Issue by diegoberpan** [microsoft/PlanetaryComputer#251]
To whom it may concern,

I have noticed that no data is retrieved after 29th July 2023. Just to let you know. Hope it is something easy to solve.

Thank you!

**Comment by TomAugspurger** [comment]
Thanks for the report, and apologies for forgetting to post an update here.

We fixed the issue that was blocking the pipeline when you reported this issue, and the most recent items in our STAC API are from today.
