### ISSUE TITLE
Planetary Computer stac catalog is not accessible 

### ISSUE THREAD

**Issue by gtgrp-user** [microsoft/PlanetaryComputer#262]
Hi, 

I am trying to access the stac catalog using the following piece of code

`from pystac_client import Client
URL = 'https://planetarycomputer.microsoft.com/api/stac/v1'
cat = Client.open(URL)
cat`

And getting the following error 
`APIError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with url: /api/stac/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f0a547e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

**Comment by TomAugspurger** [comment]
That should be working. Here's my local session:

```python
In [3]: from pystac_client import Client; URL = 'https://planetarycomputer.microsoft.com/api/stac/v1'; cat = Client.open(URL); cat
Out[3]: <Client id=microsoft-pc>
```

I wonder if you have a firewall or network setting blocking access. Can you access https://planetarycomputer.microsoft.com/api/stac/v1 on a browser, either on that same machine or a different one on a different network?

**Comment by TomAugspurger** [comment]
The error message in https://github.com/stac-utils/pystac-client/issues/383 is a bit different (custom cert vs. DNS error) but maybe some of the links there will be helpful.

**Comment by gtgrp-user** [comment]
> That should be working. Here's my local session:
> 
> ```python
> In [3]: from pystac_client import Client; URL = 'https://planetarycomputer.microsoft.com/api/stac/v1'; cat = Client.open(URL); cat
> Out[3]: <Client id=microsoft-pc>
> ```
> 
> I wonder if you have a firewall or network setting blocking access. Can you access https://planetarycomputer.microsoft.com/api/stac/v1 on a browser, either on that same machine or a different one on a different network?

The frustrating aspect is that sometimes I can access the catalog, while other times I can't, and I can indeed access the STAC URL. I'll investigate the issue with the pystac-client

**Comment by gtgrp-user** [comment]
This is no longer an issue, I can now access the STAC endpoint.

**Comment by gtgrp-user** [comment]
Hi @TomAugspurger 

The information you provided didn't offer much assistance in our specific situation. I've confirmed that I'm not utilizing a proxy server and attempted to resolve the issue by disabling the firewall, yet the intermittent APIError mentioned earlier persists.

I attempted to replicate the issue on the Planetary Computer Hub, even trying it with CPU instances, but unfortunately, I couldn't access the platform. Similarly, I encountered the same issue while using the Digital Earth Africa sandbox, both on my home network and mobile hotspot.

I've been a regular user of your STAC catalog for quite some time without any issues, up until last week.

**Comment by TomAugspurger** [comment]
Interesting, thanks.

> Just so you know, occassionaly, I receive this APIError too;

That is a somewhat known issue that we're looking into. In the meantime, https://pystac-client.readthedocs.io/en/stable/usage.html#configuring-retry-behavior has the documentation for configuring retries in pystac-client, or anything that uses urllib3.

It's hard to say, but "Temporary failure in name resolution" really does sound like a networking issue between your machine and the Planetary Computer's API servers.

**Comment by gtgrp-user** [comment]
"Temporary failure in name resolution" is indeed a network issue. 

I have configured retries in pystac-client and still geting APIError for landsat collections. However, sentinel 2 L2A, ESA and ESRI landcover  collections are working fine.

Error encountered:
`APIError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with url: /api/stac/v1/search (Caused by ResponseError('too many 503 error responses'))
`

**Comment by mehran66** [comment]
@gtgrp-user  that issue has occured on my side too...did you figure it out?

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0UYcdZQAAAADSxwGZbLbCR4ywAGvllIoWTU5aMjIxMDYwNjExMDQ1ADkyN2FiZmE2LTE5ZjYtNGFmMS1hMDlkLWM5NTlkOWExZTY0NA==</span></div></div></body></html>

**Comment by TomAugspurger** [comment]
@mehran66 that indicates an error somewhere on the service's end. You might want to add retries on whatever request generated that error (that response probably had a 500 status code).

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
