### ISSUE TITLE
No items found March-November 2022 for modis-64A1-061

### ISSUE THREAD

**Issue by Alex-Mackie** [microsoft/PlanetaryComputer#263]
When querying [Modis Burned Area Monthly](https://planetarycomputer.microsoft.com/dataset/modis-64A1-061) there are no results returned for 9 months of 2022. I would expect there to 2412 items found in line with the same period in other years.

I checked 2010-present and there is data available for all other months in that time period except these 9 months.

```
collection_name = "modis-64A1-061"

start_date = "2022-03-01"
end_date = "2022-11-01"
time_range = f"{start_date}/{end_date}"

catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)

items = catalog.search(
    collections=[collection_name], 
    datetime=time_range
    ).item_collection()

print(f"Found: {len(items)} items")
```
> Found: 0 items

Seems similar to #136

**Comment by TomAugspurger** [comment]
Thanks for the report! I'll take a look.

**Comment by TomAugspurger** [comment]
March - September 2022 should be in now. I messed up the date in my command, so October-November will roll in sometime over the next day. I'll close this out once those are in.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
