### ISSUE TITLE
Missing sentinel 2 asset

### ISSUE THREAD

**Issue by jessjaco** [microsoft/PlanetaryComputer#264]
The following asset appears to be missing. I looked for similar issues related to Sentinel 2, not sure I found any that exactly matched.

```
import planetary_computer
import rioxarray

url = "https://sentinel2l2a01.blob.core.windows.net/sentinel2-l2/56/M/MB/2023/02/14/S2B_MSIL2A_20230214T001719_N0400_R116_T56MMB_20230214T095023.SAFE/GRANULE/L2A_T56MMB_A031030_20230214T001719/IMG_DATA/R10m/T56MMB_20230214T001719_B04_10m.tif"

signed_url = planetary_computer.sign(url)
rioxarray.open_rasterio(signed_url)
```
gives
```
rasterio.errors.RasterioIOError: etc etc... not recognized as a supported file format.
```

If I try and download from the signed url I get
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:967d36f8-601e-002a-2154-e335be000000
Time:2023-09-09T19:31:22.6901287Z</Message></Error>
```

**Comment by TomAugspurger** [comment]
Thanks for the report. We recently, learned about a few of these partial scenes. We'll be going through and finding all of these, and replacing them with fixed versions.

Unfortunately, a processing timestamp is present in the item ID and paths. So both of those will change. We'll eventually delete the old items and assets, once they've been replaced.

This should be already fixed for new scenes.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.

**Comment by jessjaco** [comment]
This is still not working.
