### ISSUE TITLE
Hub notebook server not starting

### ISSUE THREAD

**Issue by TomAugspurger** [microsoft/PlanetaryComputer#267]
When logging into the Hub and selecting an environment, the logs seem stuck at "Server requested"

<img width="960" alt="image" src="https://github.com/microsoft/PlanetaryComputer/assets/1312546/316f2bab-a199-4cfd-8cad-5506422e1c03">

Looking into this now.

**Comment by mattsmiScientific** [comment]
Thanks @TomAugspurger, mine scheduling too now, though getting interesting messages in the event log
![image](https://github.com/microsoft/PlanetaryComputer/assets/93515029/c8e88d4f-c42f-4ad6-979e-c3d270769037)

**Comment by mattsmiScientific** [comment]
@TomAugspurger Keep getting spawn failed due to server taking longer than 30 seconds to reply. I have quite a lot of data in my image - could it be an over-early timeout issue?

**Comment by mattsmiScientific** [comment]
That could be me. Please don't delete the data (I need to back up my notebooks, the actual data itself could be regenerated).
________________________________

**Comment by TomAugspurger** [comment]
I just increased the size of your disk, if you want to try again.

BTW, https://planetarycomputer.microsoft.com/docs/overview/environment/#understanding-the-file-system recommends just storing code and notebooks in your home directory. Large outputs should go somewhere like Blob Storage.

And yes, backups are always a good idea :)

**Comment by mattsmiScientific** [comment]
Thanks @TomAugspurger  yes that worked. Thanks. You are absolutely right about blob storage - I was obsessing about solving one problem and not seeing the other!

**Comment by mattsmiScientific** [comment]
Thanks for the incredible support @TomAugspurger :-)

**Comment by gkenyon99** [comment]
Hi @TomAugspurger I think I am having the same issue and my directory is full. my username is sggkenyo@liverpool.ac.uk. Please could you help me get access today? I really need it for a journal deadline, thanks
