### ISSUE TITLE
missing STAC-Items for Sentinel-2-L2A

### ISSUE THREAD

**Issue by 11904212** [microsoft/PlanetaryComputer#269]
Hi,
I have noticed that some STAC items seem to be missing in the "sentinel-2-l2a" collection.

Here is an example [query](
https://planetarycomputer.microsoft.com/api/stac/v1/search?collections=sentinel-2-l2a&datetime=2022-01-24T00:00:00.000Z/2022-01-26T23:59:59.999Z&bbox=14.258,47.888,14.293,47.908) (0 results)

Here is the same query for the [collection of element84](https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-l2a&datetime=2022-01-24T00:00:00.000Z/2022-01-26T23:59:59.999Z&bbox=14.258,47.888,14.293,47.908) (1 result) and the a link to the [scihub product](https://scihub.copernicus.eu/dhus/odata/v1/Products('36cefeea-2848-495f-9af3-85ce8f22cfb9')/$value)

I've noticed these gaps a few times and was wondering where they originated from.

**Comment by TomAugspurger** [comment]
Thanks for the report @11904212. I'm not sure why, but it seems like our pipeline missed scenes around that date.

We are working on a census for all of our assets, to ensure that they match what's provided from our upstream data provider. In the meantime, we'll get those reprocessed.

**Comment by KBodolai** [comment]
Just to add here, got about 4 missing ones with this search:

```python
miny, minx = -1.5,35
maxy, maxx = -0.5,39

bbox = [minx, miny, maxx, maxy]

mpc_items = mpc_catalog.search(collections='sentinel-2-l2a',bbox=bbox,datetime='2022-08-28').item_collection()

# len(mpc_items) =  0
```

and the 4 items as apparent in a similar search in the copernicus dataspace browser:

![image](https://github.com/microsoft/PlanetaryComputer/assets/69843715/de0e0df1-cfa2-4dcd-aff7-d6837d393375)

I wrote a small script that finds searches with missing data, @TomAugspurger , would it be helpful if I ran it and sent a bunch? I'm guessing you have something better at hand for the census of the assets, but let me know if I can help in any way!

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
