### ISSUE TITLE
Sentinel-1 GRD geolocation

### ISSUE THREAD

**Issue by harryC-space-intelligence** [microsoft/PlanetaryComputer#272]
Sentinel-1 GRD data in some regions are not well geolocated.

For example at (lat = 1.015326, lon= -76.483238): 

![image](https://github.com/microsoft/PlanetaryComputer/assets/140395181/409d5346-4979-4445-919e-c48ff472108a)

This image is the mean from all of the data-takes in 2020 (relative orbit 142), suggesting this is a systematic issue with how the data are georeferenced.

After trying randomly 3 other areas, I found another example at (-8.968573,26.672217):

![image](https://github.com/microsoft/PlanetaryComputer/assets/140395181/d4680bbf-d827-4ada-9c5c-1fd97b6eaba2)

The RTC products are not affected.

Is this issue known / intentional? I do not understand what is meant by "The ellipsoid projection of the GRD products is corrected using the terrain height specified in the product general annotation. The terrain height used varies in azimuth but is constant in range (but can be different for each IW/EW sub-swath)" -- is this processing chain documented somewhere?

**Comment by TomAugspurger** [comment]
My limited understanding is that GRD products will often of this issue, and that RTC is provided to solve this exact problem.

We have https://planetarycomputer.microsoft.com/docs/tutorials/customizable-rtc-sentinel1/, which goes into some of the background. Our RTC product uses a different algorithm than `sarsen` but it's the same general idea.

The upstream ESA documentation linked from the dataset detail page probably has more information.
