### ISSUE TITLE
Cant log in through VSCODE

### ISSUE THREAD

**Issue by mattsmiScientific** [microsoft/PlanetaryComputer#273]
I'm failing to connect to my Planetary Computer instance through VS Code. 

I follow the steps 1,2,2,3 at https://planetarycomputer.microsoft.com/docs/overview/ui-vscode/

I tried to follow step 4 but I see the method has changed. So I do as described in the first two steps here
https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev
(basically make a new notebook and then Select "Existing Jupyter Server"... and enter the URI of the Jupyter server)

When I need to enter the URI of my Jupyter server I use the one indicated in the documentation of  https://planetarycomputer.microsoft.com/docs/overview/ui-vscode/
as in
"https://pccompute.westeurope.cloudapp.azure.com/compute/user/<YOUR_EMAIL>/?token=<YOUR_TOKEN>"

But with my username and the API token I generated at https://pccompute.westeurope.cloudapp.azure.com/compute/hub/token

My experience is then different from described because I then get asked to enter my username and password. First I enter my user name, then I enter my password (which I assume is my O365 credentials)
<img width="460" alt="image" src="https://github.com/microsoft/PlanetaryComputer/assets/93515029/f1f77f78-0f07-4b95-84b8-30c586afca64">

This seems to do something because I then get asked to change my server display name
![image](https://github.com/microsoft/PlanetaryComputer/assets/93515029/7ed635d3-cbf3-4ad8-a9d1-db13dfec2b7f)

No matter what I do then, it says it is "unable to connect to the remote server, ensure the server is running and reachable"

The API hub does note that a connection was tried. I kept suspecting I'd got the wrong password but I'm now wondering if it's that the server is blocking access some other way. Any advice? Thanks M

**Comment by TomAugspurger** [comment]
I'm not sure, I haven't tried using VS Code's remote server support in a while. In https://github.com/microsoft/PlanetaryComputer/discussions/268 someone else was running into this.

> My experience is then different from described because I then get asked to enter my username and password. First I enter my user name, then I enter my password (which I assume is my O365 credentials)

I'm not 100% sure, but I would guess that your O365 credentials won't work there. For the oauth2 flow to work, I would think you'd need to be redirected to the Microsoft login page. I'm not sure what credentials it's asking for :/

**Comment by mattsmiScientific** [comment]
Thanks Tom. Yes #268 looks to be exactly the same issue. I wondered about the username and password (given the URI has username and API key) and tried leaving them blank... but otherwise not sure what would make sense to try. Perhaps this is not the best method. I was just going for an easy solution to execute my notebooks on the PC Server.

**Comment by mattsmiScientific** [comment]
There is also this point made on the various VScode connection instructions, that requires a command to be run at the server side. However, I would expect you've already done this
<img width="672" alt="image" src="https://github.com/microsoft/PlanetaryComputer/assets/93515029/bbedabe7-bc0a-44dd-8f8c-1a34bc8c3c11">

**Comment by mattsmiScientific** [comment]
also 
<img width="544" alt="image" src="https://github.com/microsoft/PlanetaryComputer/assets/93515029/e397d76b-dd2a-4604-9be9-1727dbcb573c">
from https://code.visualstudio.com/docs/datascience/notebooks-web

**Comment by mattsmiScientific** [comment]
> I am having the same issue. Has anyone found a solution yet?

No but I just managed to do it on my own private planetary computer instance. I don't fully understand what is going on but perhaps this helps. When I log on to [my private planetary computer URL]/hub/token, I can create my own API token. I noticed that in the top right there is a name, which is my first and last name with a space "matthew smith". It's not my email address, it must be the "user name" associated with my email address. I thought I would try that and my API key as the password and it worked!

The trouble is, when I go to get a similar name for my microsoft hosted planetary computer hub it doesn't show anything. So I still cannot get that version to work. But perhaps you can try with different possibilities of what your user name could be. It's frustrating, but in my case I've coincidentally bypassed the problem by setting up my own PC instance.

@TomAugspurger

**Comment by TomAugspurger** [comment]
I'm not sure either, and haven't had a chance to investigate.
________________________________

**Comment by jgomezdans** [comment]
Just adding that I had the same experience with this.

**Comment by AbdulNajah** [comment]
it seems to be working for me now.

**Comment by mattsmiScientific** [comment]
Great - did you change anything?

**Comment by AbdulNajah** [comment]
> Great - did you change anything?

No, I did not. just connected as a jupyterhub and tried again

**Comment by ghidalgo3** [comment]
The hub is no longer available.
