### ISSUE TITLE
Occassional missing 3dep data (hag, dtm, etc)

### ISSUE THREAD

**Issue by tonzowonzo** [microsoft/PlanetaryComputer#283]
Currently I've been looking into using Planetary Computer for downloading 3dep DTMs and height above ground imagery but I've found there's sometimes missing data when comparing to TNM (The National Map). An example location of this happening is at the coordinates: -87,33164 46,27976

Images attached are from Planetary Explorer and TNM. We've found these images are also missing when using the planetary_computer Python API.

I was wondering if there's any reason these and other images are missing or were they simply not processed?

<img width="1465" alt="image" src="https://github.com/microsoft/PlanetaryComputer/assets/35193581/35850e7f-aa66-4491-be49-12c8d8085471">
<img width="1460" alt="image" src="https://github.com/microsoft/PlanetaryComputer/assets/35193581/183d332f-6670-4456-841e-952cab10720f">

Thanks for your time,
Tim

**Comment by TomAugspurger** [comment]
Sorry for the delay; I thought I replied here.

When we initially developed the pipeline to produce the COPIC files and derived COGs, we turned up a number of issues with the source files which were reported upstream to USGS. Perhaps those have been fixed now. At some point we'll try regenerating those assets, but we don't have an ETA right now.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
