### ISSUE TITLE
DOC: ERA5 - PDS stops at 2020-12

### ISSUE THREAD

**Issue by raybellwaves** [microsoft/PlanetaryComputer#284]
In https://planetarycomputer.microsoft.com/dataset/era5-pds#overview the metadata on the right says "Temporal Extent
01/01/1979 – Present" This is not true as the ERA5 PDS data only goes up 12/31/2020.

![Screenshot 2023-10-20 at 10 52 24 AM](https://github.com/microsoft/PlanetaryComputer/assets/17162724/a6e4cfbc-3fe4-4e0e-b2bc-aefc626a6dba)

**Comment by TomAugspurger** [comment]
Yeah, the intent is for it to be true, but we've had issues with setting up a dynamic pipeline to pull new scenes :/

**Comment by Real-Slin-Shady** [comment]
Is there any news on this issue?

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
