### ISSUE TITLE
Impossible to retrieve goes-r lst data due to faulty documentation

### ISSUE THREAD

**Issue by Berhinj** [microsoft/PlanetaryComputer#300]
[Microsoft planetary computer documentation about getting goes lst ](https://planetarycomputer.microsoft.com/dataset/storage/goes-lst) data is insufficient to get that data. 

Let me explain, here is an example of a goes image url:

[https://goeseuwest.blob.core.windows.net/noaa-goes16/ABI-L2-LSTC/2023/008/12/OR_ABI-L2-LSTC-M6_G16_s20230081201170_e20230081203543_c20230081205077.nc](https://goeseuwest.blob.core.windows.net/noaa-goes16/ABI-L2-LSTC/2023/008/12/OR_ABI-L2-LSTC-M6_G16_s20230081201170_e20230081203543_c20230081205077.nc))

Notice that directory name is fully predictable while the image file path basename is not because it contains the processing timestamp which will vary of few milliseconds from a goes image to another. The way GCP and AWS deal with that is by providing bucket path instead of URL/URI, so the user can list image paths in specific folders. Another solution would be providing a data catalog, either a stac or a parquet file, like you guys are already doing with other GOES products.

Or am I missing something?

**Comment by Berhinj** [comment]
@TomAugspurger - aw something I missed which might explain part of my confusion, it doesn't for cogs though:

```
import adlfs

fs = adlfs.AzureBlobFileSystem("goeseuwest")  # storage account name
fs.ls("noaa-goes-cogs/goes-16/")  # container name + path in storage container
```

gets me

```
ClientAuthenticationError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:3f425daf-101e-0072-13b8-26178f000000
Time:2023-12-04T13:49:53.3594625Z
ErrorCode:NoAuthenticationInformation
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:3f425daf-101e-0072-13b8-26178f000000
Time:2023-12-04T13:49:53.3594625Z</Message></Error>
```

**Comment by Berhinj** [comment]
Sorry to continuously reopen the topic, I managed to access the storage and the cogs thanks to your indication

Goes lst [documentation](https://planetarycomputer.microsoft.com/dataset/storage/goes-lst) says:

"Data are available in Blob Storage in the West Europe Azure data center1, in both [NetCDF](https://www.unidata.ucar.edu/software/netcdf/) and [cloud-optimized GeoTIFF](https://www.cogeo.org/) (COG) format."

I feel like this is very misleading as less than 1% of goes-16/17/18 (for either LSTM/LSTC/LSTF) is available in COG for 2018-2023. Shouldn't it be updated accordingly? Or do you know who can I contact for that topic?

Do you have any vision, if Microsoft Planetary Computer plans on making the rest of the cogs available?


As I feel like the documentation regarding accessing COGS was lacking here is reproducable example on how to search and access goes cogs data.


```
import fsspec
import requests
import rioxarray as rxr
import planetary_computer

# Replace with your actual collection ID or storage account details
storage_account = "goeseuwest"
container = "noaa-goes-cogs"

# Function to get a token (in this context based on storage_account/container and not a collection id)
response = requests.get(f"https://planetarycomputer.microsoft.com/api/sas/v1/token/{storage_account}/{container}")
storage_token = response.json().get("token")

fs = fsspec.filesystem(protocol="abfs",
                       account_name="goeseuwest",
                      sas_token=token_data_storage["token"])
# Looking for an image
fs.ls("noaa-goes-cogs/goes-16/ABI-L2-LSTC/2023")

# Once you found your image, read it
url = 'https://goeseuwest.blob.core.windows.net/noaa-goes-cogs/goes-16/ABI-L2-LSTM/2023/201/21/OR_ABI-L2-LSTM1-M6_G16_s20232012100288_e20232012100345_c20232012100543_LST.tif'
rxr.open_rasterio(planetary_computer.sign(url))
```

**Comment by Berhinj** [comment]
That'd be super valuable for us, thanks a lot

**Comment by Berhinj** [comment]
Any news on this?

**Comment by TomAugspurger** [comment]
I haven't had a chance to. If you want, you could try looking through the directories in the goeseuwest/noaa-goes-cogs container.

________________________________

**Comment by Berhinj** [comment]
I'm giving up on this, found better data sources
