### ISSUE TITLE
Sentinel-1 Datasets Should Have Local Incidence Angle layer 

### ISSUE THREAD

**Issue by EkulRF** [microsoft/PlanetaryComputer#302]
Sentinel-1 datasets should have associated local incidence angle (LIA) layer associated with any given image, I believe they are found under tie-points Grids. This is really crucial for a lot of SAR applications, so would appreciate this being added to the Planetary Computer suite. (Unless I'm blind and haven't spotted it - in which case, how can I access this layer!)

https://forum.step.esa.int/t/incidence-angle-sentinel-1-image/8105

**Comment by TomAugspurger** [comment]
See the discussion at https://github.com/microsoft/PlanetaryComputer/discussions/279#discussioncomment-7635426 (we don't have it currently, but depending on user feedback we might be able to someday in the future).

I'll close this so we can keep the discussion consolidated in https://github.com/microsoft/PlanetaryComputer/discussions/279

**Comment by EkulRF** [comment]
Hi Thank you for this.

Can I also ask for the View Angle Layer to be added?

**Comment by TomAugspurger** [comment]
We can track those at the same time. You might want to post that request in #279.
