### ISSUE TITLE
Bad bounding box for Landsat 9 Item

### ISSUE THREAD

**Issue by jessjaco** [microsoft/PlanetaryComputer#305]
Landsat 9 item with id `LC09_L2SR_073073_20231109_02_T2` has an incorrect bounding box of `[-242.00149752, -19.84166403, -117.33451435, -17.73297939]`

https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC09_L2SR_073073_20231109_02_T2

**Comment by jessjaco** [comment]
Another one: Landsat 8 item with id `LC08_L2SR_075066_20231030_02_T1` has an incorrect bounding box of `[
111.79724071,
-9.738496,
246.70120949,
-7.62132555
]`. The geometry is bad too

https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-c2-l2/items/LC08_L2SR_075066_20231030_02_T1

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.

**Comment by jessjaco** [comment]
These were not fixed
