### ISSUE TITLE
Request for PDAL update

### ISSUE THREAD

**Issue by camipawlak** [microsoft/PlanetaryComputer#308]
Hi there- thanks to the planetary computer team for all the work they do keeping this platform going and updated, I really appreciate it!

Any chance there will be an update for the PDAL package soon to version 2.6.0 or above for the hub environment? Right now at 2.5.5, the faceraster filter doesn't have the option to set the max_triangle_edge_length, which is helpful for creating more custom lidar processing steps. https://pdal.io/en/2.6.0/stages/filters.faceraster.html#filters-faceraster

**Comment by TomAugspurger** [comment]
Thanks, I'll try to get these updated on Hub soon-ish, but it likely won't be till after the New Year.

**Comment by camipawlak** [comment]
Thank you and happy new year!

**Comment by TomAugspurger** [comment]
The Python image now has pdal 2.6.3: https://github.com/microsoft/planetary-computer-containers/blob/e61a785bad14008ac4b858b0847ef46d4a34631a/python/conda-linux-64.lock#L690. Let me know if you spot any issues.
