### ISSUE TITLE
Sentinel-2 imagery is smeared out intermittently

### ISSUE THREAD

**Issue by pkopparla** [microsoft/PlanetaryComputer#312]
Occasionally, Sentinel-2 images in the RGB bands are totally smeared out. An example is attached showing both clear and blurred out images for a location. 
![image](https://github.com/microsoft/PlanetaryComputer/assets/76039838/a93e1746-2f3d-4b21-abe3-10c473c54f85)
![image](https://github.com/microsoft/PlanetaryComputer/assets/76039838/1cf0c3a6-9b60-4549-8c02-30800e82b751)

These files were accessed as follows:
1. for a 0.2x0.2 lat lon area of interest centered around [25.81, -10.78] (lon, lat). 
2. this is the 'visual' asset for the catalog item. 
3. only filtering for cloud percentage under 20 for this location for each month of 2021.

Jan, Feb and Dec have no non-cloudy images, usable images are downloaded for Mar, Apr and Oct, rest are blurred out. I do not know what is causing this issue.

Other points of interest: whether an image is blurred out or not for a given time/location also seems to depend on the size of the area of interest. Typically the months for which blurred images appear seem to have >10 cloudless items per month, which is unusual given the Sentinel-2 revisit frequency. Normal image yielding months have <6.

I'm using a blur detector after downloading the image to filter for bad images. It would be good if these are flagged and removed from the repository as it's a waste of bandwidth for both of us.

**Comment by TomAugspurger** [comment]
Thanks for the report. Do you happen to know if the source L1C images are blurry as well? I'm wondering if this is an issue with the data when it was detected (so it would also affect L1C imagery available from e.g. https://dataspace.copernicus.eu/ too) or with our L1C to L2A processing.

Do you have the STAC item ID of the blurry handy?

**Comment by pkopparla** [comment]
I haven't checked the level 1 images. Here are the IDs of several blurry images:
{'mutanda_05_2021': 'S2A_MSIL2A_20210530T081601_R121_T35LLH_20210605T231139'}, 
{'mutanda_06_2021': 'S2A_MSIL2A_20210609T081601_R121_T35LLH_20210612T174214'}, 
{'mutanda_07_2021': 'S2B_MSIL2A_20210714T081609_R121_T35LLH_20210714T233359'}, 
{'mutanda_08_2021': 'S2A_MSIL2A_20210808T081611_R121_T35LLH_20210808T184738'}, 
{'mutanda_09_2021': 'S2B_MSIL2A_20210912T081559_R121_T35LLH_20210912T163400'}

**Comment by Ahleroy** [comment]
I have had similar issues in the past with L2A data.
Having access to L1C data from the PC would be interesting in such a scenario as well.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
