### ISSUE TITLE
Wrong file names on STAC metadata for Sentinel 1 GRD products

### ISSUE THREAD

**Issue by jgomezdans** [microsoft/PlanetaryComputer#313]
I have found that some Sentinel 1 GRD products link to the wrong file. Changing the file to what ought to be works, so I guess that there's a bug in building up the STAC metadata. For example, in some files, the `schema-product-vv` asset points to `/rfi/rfi-iw-vv.xml`, rather than `/iw-vv.xml`. 

It's easily solved by hard-coding the filename in the URL, and I only noticed it in some granules. Just flagging it here.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
