### ISSUE TITLE
Missing S2 L2A data

### ISSUE THREAD

**Issue by Ahleroy** [microsoft/PlanetaryComputer#317]
I found that some data were missing from the Sentinel-2 L2A database.

I cannot access the latest data from the region. They are supposed to be a few days old and I usually access them quickly.

Below is an example of the data not being found using the Planetary Computer. If one changes the STAC URL for element 84, the missing data can be found.

```python 
import pystac_client
import planetary_computer


catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1", # Does NOT find the last items
    #"https://earth-search.aws.element84.com/v1", # Finds the last items

    modifier=planetary_computer.sign_inplace,
)

area_of_interest = {
                "type": "Point",
                "coordinates": [ -53.9813, 3.64753],
            }

date_time = "2024-01-29/2024-02-07"
search = catalog.search(collections=["sentinel-2-l2a"],
                            intersects=area_of_interest,
                            datetime=date_time,
                            )

items = search.item_collection()

print("NUM ITEMS FOUNDS: ", len(items))

```

**Comment by TomAugspurger** [comment]
Our data pipelines have been seeing an elevated number of errors fetching L1C data from our upstream data provider. We do have processes that catch up and retries scenes that failed to download previously. I'll check in on these ones specifically.

**Comment by toutas** [comment]
generally s2 data after 2024-02-01 is missing

**Comment by TomAugspurger** [comment]
Sorry about that, all of these times are in now. That search is correctly returning two items.
