### ISSUE TITLE
Planetary computer timeouts for the past few hours

### ISSUE THREAD

**Issue by toutas** [microsoft/PlanetaryComputer#318]
Requests keep failing with "request exceeded the maximum allowed time" for planetary computer today, regardless of the country I  perform the request from. 

Attempting to access sentinel 2 if that makes a difference.

**Comment by TomAugspurger** [comment]
We had some really high load causing timeouts for some requests. We've applied some fixes and service should be back to normal, but let us know if you spot any issues.
