### ISSUE TITLE
Missing data in the Copernicus DEM 30m 

### ISSUE THREAD

**Issue by polSARfeatures** [microsoft/PlanetaryComputer#319]
Hi everyone!
In higher latitudes, there are 1 pixel gaps in the data values between tiles for the Copernicus 30m DEM. The gaps are due to nan values on the tile borders, and not to a geometry issue.

When getting data over Denmark, for example from longitudes 10 to 12 deg and latitudes 55 to 57 deg, there is a gap in the data in the longitude between tiles, as shown here:

![dk_qgis](https://github.com/microsoft/PlanetaryComputer/assets/114110631/af67a4fb-9642-4337-ab39-849f53f9f66e)

In higher latitudes, it seems the issue also arises in the latitude between tiles. For example, over Svalbard (longitudes 11 to 13 deg, latitudes from 78 to 80 deg):
![svalbard_qgis](https://github.com/microsoft/PlanetaryComputer/assets/114110631/51421209-f7a0-4ad8-aaca-019b63b45926)

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
