### ISSUE TITLE
STAC swagger document not working

### ISSUE THREAD

**Issue by krishnaglodha** [microsoft/PlanetaryComputer#332]
I'm trying to execute swagger doc hosted at `https://planetarycomputer.microsoft.com/docs/reference/stac/`  , but facing error 
<img width="1432" alt="Screenshot 2024-03-25 at 5 35 33 PM" src="https://github.com/microsoft/PlanetaryComputer/assets/47075664/bfbeee12-4eab-4a74-93f0-08678fd64db0">

Reason I suspect is addition of `api/stac/v1/` twice
```[tasklist]
### Tasks
```

**Comment by TomAugspurger** [comment]
Thanks for the report, we'll take a look.

**Comment by TomAugspurger** [comment]
This is deployed now, and should be working:

![image](https://github.com/microsoft/PlanetaryComputer/assets/1312546/7e41822d-a3a2-4bc7-a501-fe3bd8432973)
