### ISSUE TITLE
Corrupt DEM data (3DEP Seamless)

### ISSUE THREAD

**Issue by jameslowman** [microsoft/PlanetaryComputer#336]
I found a scene that has not data (in the explorer or when downloaded) -- wanted to report it to someone. Here is the asset snippet:

{"id":"n50w123-13","bbox":[-123.000555554894,48.9994444449061,-121.999444444505,50.0005555552956],"type":"Feature","links":[{"rel":"collection","type":"application/json","href":"https://planetarycomputer.microsoft.com/api/stac/v1/collections/3dep-seamless"},{"rel":"parent","type":"application/json","href":"https://planetarycomputer.microsoft.com/api/stac/v1/collections/3dep-seamless"},{"rel":"root","type":"application/json","href":"https://planetarycomputer.microsoft.com/api/stac/v1/"},{"rel":"self","type":"application/geo+json","href":"https://planetarycomputer.microsoft.com/api/stac/v1/collections/3dep-seamless/items/n50w123-13"},{"rel":"via","href":"https://ai4edataeuwest.blob.core.windows.net/3dep/Elevation/13/TIFF/n50w123/USGS_13_n50w123.xml"},{"rel":"preview","href":"https://planetarycomputer.microsoft.com/api/data/v1/item/map?collection=3dep-seamless&item=n50w123-13","title":"Map of item","type":"text/html"}],"assets":{"data":{"href":"https://ai4edataeuwest.blob.core.windows.net/3dep/Elevation/13/TIFF/n50w123/USGS_13_n50w123.tif","title":"USGS 1/3 arc-second n50w123 1 x 1 degree","description":"This tile of the 3D Elevation Program (3DEP) seamless products is 1/3 arc-second resolution.  3DEP data serve as the elevation layer of The National Map, and provide basic elevation information for Earth science studies and mapping applications in the United States. Scientists and resource managers use 3DEP data for global change research, hydrologic modeling, resource monitoring, mapping and visualization, and many other applications. 3DEP data compose an elevation dataset that consists of seamless layers and a high resolution layer.  Each of these layers consists of the best available raster elevation data of the conterminous United States, Alaska, Hawaii, territorial islands, Mexico and Canada.  3DEP data are updated continually as new data become available. Seamless 3DEP data are derived from diverse source data that are processed to a common coordinate system and unit of vertical measure. These data are distributed in geographic coordinates in units of decimal degrees, and in conformance with the North American Datum of 1983 (NAD 83). All elevation values are in meters and, over the conterminous United States, are referenced to the North American Vertical Datum of 1988 (NAVD 88). The vertical reference will vary in other areas. Seamless 3DEP data are available nationally (except for Alaska) at resolutions of 1 arc-second (approximately 30 meters) and 1/3 arc-second (approximately 10 meters). In most of Alaska, only lower resolution source data are available. As a result, most seamless 3DEP data for Alaska are at 2 arc-second (approximately 60 meters) grid spacing. Part of Alaska is available at the 1 and 1/3 arc-second resolutions from interferometric synthetic aperture radar (ifsar) collections starting in 2010.  Plans are in place for collection of statewide ifsar in Alaska. All 3DEP products are public domain.","type":"image/tiff; application=geotiff; profile=cloud-optimized","roles":["data"]},"gpkg":{"href":"https://ai4edataeuwest.blob.core.windows.net/3dep/Elevation/13/TIFF/n50w123/n50w123.gpkg","type":"application/geopackage+sqlite3","roles":["metadata"]},"metadata":{"href":"https://ai4edataeuwest.blob.core.windows.net/3dep/Elevation/13/TIFF/n50w123/USGS_13_n50w123.xml","type":"application/xml","roles":["metadata"]},"thumbnail":{"href":"https://ai4edataeuwest.blob.core.windows.net/3dep/Elevation/13/TIFF/n50w123/USGS_13_n50w123.jpg","type":"image/jpeg","roles":["thumbnail"]},"tilejson":{"title":"TileJSON with default rendering","href":"https://planetarycomputer.microsoft.com/api/data/v1/item/tilejson.json?collection=3dep-seamless&item=n50w123-13&assets=data&colormap_name=terrain&rescale=-1000%2C4000&format=png","type":"application/json","roles":["tiles"]},"rendered_preview":{"title":"Rendered preview","rel":"preview","href":"https://planetarycomputer.microsoft.com/api/data/v1/item/preview.png?collection=3dep-seamless&item=n50w123-13&assets=data&colormap_name=terrain&rescale=-1000%2C4000&format=png","roles":["overview"],"type":"image/png"}},"geometry":{"type":"Polygon","coordinates":[[[-121.99944444,48.99944444],[-121.99944444,50.00055556],[-123.00055555,50.00055556],[-123.00055555,48.99944444],[-121.99944444,48.99944444]]]},"collection":"3dep-seamless","properties":{"gsd":10,"datetime":"2018-02-02T00:00:00Z","proj:epsg":5498,"proj:shape":[10812,10812],"proj:transform":[0.000092592593,0.0,-123.000555554894,0.0,-0.000092592593,50.0005555552956,0.0,0.0,1.0],"threedep:region":"n50w130"},"stac_extensions":["https://stac-extensions.github.io/projection/v1.0.0/schema.json"],"stac_version":"1.0.0"}

**Comment by TomAugspurger** [comment]
Thanks for the report, we'll look into it.

Interestingly it's only the 1/3rd arc-second asset that's affected. The 1 arc-second item at https://planetarycomputer.microsoft.com/api/stac/v1/collections/3dep-seamless/items/n50w123-1 looks fine.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
