### ISSUE TITLE
Land cover classification tutorial start issue

### ISSUE THREAD

**Issue by heksam** [microsoft/PlanetaryComputer#337]
Hi! 
Im trying out the land cover classification tutorial, but cant get past the first part of code. I have tried "pip install dask_cuda" in a terminal, but then this error pops up. I have tried other ways to install in terminal (and also in the notebook itself), but nothing works. Has anyone got a clue of what I could do? I dont understand why I need to install packages to run tutorials provided by planetary computer.

ImportError                               Traceback (most recent call last)
File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/array/__init__.py:4
      3 try:
----> 4     from dask.array import backends, fft, lib, linalg, ma, overlap, random
      5     from dask.array.blockwise import atop, blockwise

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/array/fft.py:17
     16 from dask.array.core import concatenate as _concatenate
---> 17 from dask.array.creation import arange as _arange
     18 from dask.array.numpy_compat import NUMPY_GE_200

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/array/creation.py:26
     25 from dask.array.numpy_compat import AxisError
---> 26 from dask.array.ufunc import greater_equal, rint
     27 from dask.array.utils import meta_from_array

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/array/ufunc.py:10
      9 from dask.array.core import Array, apply_infer_dtype, asarray, blockwise, elemwise
---> 10 from dask.base import is_dask_collection, normalize_function
     11 from dask.highlevelgraph import HighLevelGraph

ImportError: cannot import name 'normalize_function' from 'dask.base' (/srv/conda/envs/notebook/lib/python3.11/site-packages/dask/base.py)

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/dataframe/__init__.py:98
     97 from dask.base import compute
---> 98 from dask.dataframe import backends, dispatch, rolling
     99 from dask.dataframe.core import (
    100     DataFrame,
    101     Index,
   (...)
    107     to_timedelta,
    108 )

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/dataframe/backends.py:10
      8 from pandas.api.types import is_scalar, union_categoricals
---> 10 from dask.array.core import Array
     11 from dask.array.dispatch import percentile_lookup

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/array/__init__.py:273
    267 msg = (
    268     "Dask array requirements are not installed[.\n\n](https://pccompute.westeurope.cloudapp.azure.com/compute/user/mfl083@uib.no/lab/tree/PlanetaryComputerExamples/tutorials/n/n)"
    269     "Please either conda or pip install as follow[s:\n\n](file:///S:/n/n)"
    270     "  conda install dask                 # either conda install\n"
    271     '  python -m pip install "dask[array]" --upgrade  # or python -m pip install'
    272 )
--> 273 raise ImportError(str(e) + "\n\n" + msg) from e

ImportError: cannot import name 'normalize_function' from 'dask.base' (/srv/conda/envs/notebook/lib/python3.11/site-packages/dask/base.py)

Dask array requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                 # either conda install
  python -m pip install "dask[array]" --upgrade  # or python -m pip install

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[2], line 2
      1 from dask.distributed import Client
----> 2 from dask_cuda import LocalCUDACluster
      4 cluster = LocalCUDACluster(threads_per_worker=4)
      5 client = Client(cluster)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask_cuda/__init__.py:8
      6 import dask
      7 import dask.utils
----> 8 import dask.dataframe.core
      9 import dask.dataframe.shuffle
     10 import dask.dataframe.multi

File /srv/conda/envs/notebook/lib/python3.11/site-packages/dask/dataframe/__init__.py:159
    152     except ImportError as e:
    153         msg = (
    154             "Dask dataframe requirements are not installed[.\n\n](https://pccompute.westeurope.cloudapp.azure.com/compute/user/mfl083@uib.no/lab/tree/PlanetaryComputerExamples/tutorials/n/n)"
    155             "Please either conda or pip install as follow[s:\n\n](file:///S:/n/n)"
    156             "  conda install dask                     # either conda install\n"
    157             '  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install'
    158         )
--> 159         raise ImportError(msg) from e
    162 from dask.dataframe._testing import test_dataframe

ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install

**Comment by TomAugspurger** [comment]
Mmm, looks like I might have dropped dask-cuda when I did the update to resolve https://github.com/microsoft/PlanetaryComputer/issues/321.

In the meantime, I wonder if can work around it with something like this (untested):

```python
client = Client(threads_per_worker=4, n_workers=1)
```

instead of importing and using `LocalCUDACluster`. That'll lose some of the features dask-cuda brings, but I think we aren't using any of those (the GPU code will still run on the GPU).

**Comment by heksam** [comment]
It got me a little further, but now it stopped on the "Now let’s do some visual spot checking of our model." part in the middle. 

import matplotlib.colors
from bokeh.models.tools import BoxZoomTool
import panel
import hvplot.xarray  # noqa
etc

Here it throws a long error, bottom message saying "TypeError: argument of type 'ListedColormap' is not iterable"

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
