### ISSUE TITLE
Error in downloading Sentinel-1-rtc

### ISSUE THREAD

**Issue by LucaScalenghe** [microsoft/PlanetaryComputer#338]
Hi,
I was trying to store the data relative to a specific bbox with this script but it throws me error as if the data is not available.

```
import logging
import json
from pathlib import Path
import yaml
import pandas as pd
import numpy as np
import xarray as xr
import rioxarray
from shapely.geometry import box
import stackstac
import pystac_client
import planetary_computer
from rasterio.enums import Resampling
from extra_bands import ExtraBands
from pyproj import CRS
from pyproj import Transformer
import rich.table
from IPython.display import Image
from ast import literal_eval
from dotenv import load_dotenv
import os
import time

load_dotenv()  # take environment variables from .env.
api_key = os.getenv('PLANETARY_COMPUTER_API_KEY')

planetary_computer.settings.set_subscription_key(api_key)
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
)
time_range = "2023-12-01/2023-12-31"
bbox = (45.10458333333333, 45.894333333333336, 45.12591666666667, 45.91566666666667)

search = catalog.search(collections=["sentinel-1-rtc"], bbox=bbox, datetime=time_range)
items = search.item_collection()
print(f"Found {len(items)} items")

custom_bands = ["vv", "vh"]
output_crs = 4326


data = (
            stackstac.stack(
                items,
                assets=custom_bands,
                bounds_latlon=bbox,
                resampling=Resampling.bilinear,
                epsg=int(output_crs),
                dtype=np.float32,
                xy_coords='center',
                properties=True
                )
        )

def save_with_retry(data, output_file, max_attempts=3, delay_seconds=5):
    """
    Attempts to save the data to a raster file with retries on failure, skips if all attempts fail.
    
    Args:
    data (xarray DataArray): The data to save.
    output_file (str): The path to the output file.
    max_attempts (int): Maximum number of retry attempts.
    delay_seconds (int): Delay between retries in seconds.
    """
    attempt = 0
    while attempt < max_attempts:
        try:
            data.rio.to_raster(output_file)
            print(f"Successfully saved: {output_file}")
            return True  # Successfully saved
        except Exception as e:
            attempt += 1
            print(f"Attempt {attempt}/{max_attempts} failed with error: {e}")
            if attempt < max_attempts:
                print(f"Retrying after {delay_seconds} seconds...")
                time.sleep(delay_seconds)
            else:
                print(f"All attempts failed. Skipping {output_file}.")
                return False  # Failed to save

# Directory to save the outputs
output_dir = "./test_folder"

for timestamp in data.time.values:
    timestamp_str = pd.Timestamp(timestamp).strftime("%Y%m%dT%H%M%S")
    print(timestamp_str)
    output_file = os.path.join(output_dir, f"{timestamp_str}.nc")
    
    subdata = data.sel(time=timestamp)
    print(subdata.shape)
    
    attrs = data.attrs.copy()  # Make a copy to avoid modifying the original attributes
    attrs['bands'] = list(subdata.band.values)
    print(list(subdata.band.values))
    print(attrs.keys())
    
    subdata.rio.update_attrs(attrs, inplace=True)
    print(type(subdata))
    print(subdata.shape)
    
    if not save_with_retry(subdata, output_file):
        continue  # Skip to the next iteration if saving fails

```

This is the initial piece of the log that I have.

Found 5 items
20231204T030806
(2, 237, 162)
['vv', 'vh']
dict_keys(['spec', 'crs', 'transform', 'resolution_xy', 'bands'])
<class 'xarray.core.dataarray.DataArray'>
(2, 237, 162)
/nfs/home/scalenghe/thesis-synthetic-ndvi-s1/.venv-ndvi/lib/python3.10/site-packages/stackstac/prepare.py:408: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  times = pd.to_datetime(
/nfs/home/scalenghe/thesis-synthetic-ndvi-s1/.venv-ndvi/lib/python3.10/site-packages/stackstac/rio_reader.py:331: UserWarning: Error opening 'https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2023/12/4/IW/DV/S1A_IW_GRDH_1SDV_20231204T030753_20231204T030818_051499_063748_0400/measurement/iw-vh.rtc.tiff': RasterioIOError('HTTP response code: 404')
  warnings.warn(msg)
/nfs/home/scalenghe/thesis-synthetic-ndvi-s1/.venv-ndvi/lib/python3.10/site-packages/stackstac/rio_reader.py:331: UserWarning: Error opening 'https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2023/12/4/IW/DV/S1A_IW_GRDH_1SDV_20231204T030753_20231204T030818_051499_063748_0400/measurement/iw-vv.rtc.tiff': RasterioIOError('HTTP response code: 404')
  warnings.warn(msg)
Attempt 1/3 failed with error: Unexpected shape (237, 162), expected exactly 1 band.
Retrying after 5 seconds...
Attempt 2/3 failed with error: Error opening 'https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2023/12/4/IW/DV/S1A_IW_GRDH_1SDV_20231204T030753_20231204T030818_051499_063748_0400/measurement/iw-vh.rtc.tiff': RasterioIOError("'/vsicurl/https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2023/12/4/IW/DV/S1A_IW_GRDH_1SDV_20231204T030753_20231204T030818_051499_063748_0400/measurement/iw-vh.rtc.tiff' does not exist in the file system, and is not recognized as a supported dataset name.")
Retrying after 5 seconds...
Attempt 3/3 failed with error: Error opening 'https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2023/12/4/IW/DV/S1A_IW_GRDH_1SDV_20231204T030753_20231204T030818_051499_063748_0400/measurement/iw-vh.rtc.tiff': RasterioIOError("'/vsicurl/https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2023/12/4/IW/DV/S1A_IW_GRDH_1SDV_20231204T030753_20231204T030818_051499_063748_0400/measurement/iw-vh.rtc.tiff' does not exist in the file system, and is not recognized as a supported dataset name.")
All attempts failed. Skipping /nfs/home/scalenghe/thesis-synthetic-ndvi-s1/test/test_folder/20231204T030806.nc.

If you try to access the link it says that the data is not available

**Comment by TomAugspurger** [comment]
Can you confirm that you're using signed URLs to download the assets? See https://planetarycomputer.microsoft.com/docs/concepts/sas/.

The quickest / easiest fix is to use 

```python
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)

**Comment by LucaScalenghe** [comment]
I had this line in a previous attempt but it gave me the error that I copy here:

HTTPError: 403 Client Error: Forbidden for url: https://planetarycomputer.microsoft.com/api/sas/v1/token/sentinel1euwestrtc/sentinel1-grd-rtc


The code snippet is exactly the same as before with the addition of the suggested line. Deleting that line brought me a bit further but it seems that there is a problem with authentication in this two function calls:

```
planetary_computer.settings.set_subscription_key(api_key)
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,

)
```

**Comment by TomAugspurger** [comment]
That indicates that the API key isn't being set correctly.

Can you try running the example from the docs?

```
curl -H "Ocp-Apim-Subscription-Key: {your-api-key}" https://planetarycomputer.microsoft.com/api/sas/v1/tokenhttp://sentinel1euwestrtc/sentinel1-grd-rtc
```

or use requests and make a request with that header set? I'm wondering if there's a typo in your API key.

**Comment by manapshymyr-OB** [comment]
@TomAugspurger hi, I have been using:

```
planetary_computer.settings.set_subscription_key(subscription_key_from_manage_profile)
catalog = pystac_client.Client.open("https://planetarycomputer.microsoft.com/api/stac/v1",
                                    modifier=planetary_computer.sign_inplace)
```
it was working yesterday) to calculate NDVI from sentinel-2, while today it says 
`403 Client Error: Forbidden for url: https://planetarycomputer.microsoft.com/api/sas/v1/token/sentinel2l2a01/sentinel2-l2`
I have not changed anything ... what can be the problem?

**Comment by TomAugspurger** [comment]
Hmm, interesting. @manapshymyr-OB Could you email us at planetarycomputer@microsoft.com so we can dig into what's going on?

**Comment by BnJam** [comment]
I just ran into the same issue, using the modifier. I am able to query GRD product but not the RTC. Even with setting the API key (using the same code above). Just to confirm it's not a localised issue.

**Comment by TomAugspurger** [comment]
@BnJam the fact that sentinel-1-GRD works, but RTC doesn't, sounds a bit different.

Some datasets, like sentinel-1-rtc, *require* a Planetary Computer subscription key in the requests to get a SAS token. See https://planetarycomputer.microsoft.com/docs/concepts/sas/ for more, but you might want to double check that your `PC_SDK_SUBSCRIPTION_KEY`, or however you're setting up the `planetary_computer` package, is set correctly.

**Comment by BnJam** [comment]
Apologies; I was trying to use my JupyterHub API Token and no the Developer API Token.

**Comment by TomAugspurger** [comment]
I think the original issue is fixed, so I'll go ahead and close this.
