### ISSUE TITLE
No access to Sentinel 2A catalog today

### ISSUE THREAD

**Issue by PlekhanovaElena** [microsoft/PlanetaryComputer#344]
Dear Planetary Computer team,

I'm trying to run the standard Santinel-2A notebook from the Readme page of planetary hub: sentinel-2-l2a-example.ipynb

this chunk takes very long:
```
search = catalog.search(
    collections=["sentinel-2-l2a"],
    intersects=area_of_interest,
    datetime=time_of_interest,
    query={"eo:cloud_cover": {"lt": 10}},
)

# Check how many items were returned
items = search.item_collection()
print(f"Returned {len(items)} Items")
```

And responds with the following Error:
```
RetryError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with 
url: /api/sas/v1/token/sentinel2l2a01/sentinel2-l2 (Caused by ResponseError('too many 504 error responses'))
```

This is surprising, as I worked with Santinel-2A the last few days and everything was fine.
How could I assess the Santinel-2A collection?

Kind regards,
Elena

**Comment by krishnaglodha** [comment]
I'm also facing the same issue today

**Comment by krishnaglodha** [comment]
I'm also not able to fetch `"landsat-c2-l2"`

**Comment by rohan1chaudhari** [comment]
Same problem on my side.

**Comment by TomAugspurger** [comment]
Thanks for the report.

Just to confirm, you've including `modifier=planetary_computer.sign` when you created the pystac client? Right now the STAC API should be working fine, but with `modifier=planetary_computer.sign` that snippet will also make calls to the SAS API at https://planetarycomputer.microsoft.com/api/sas/v1`, which is currently failing.

**Comment by krishnaglodha** [comment]
Any idea when can we expect it to be working again ?

**Comment by ghidalgo3** [comment]
We're doing some infrastructure changes yesterday and today, the SAS token API should be up and running now. If there are further interruptions from the work, I will notify this thread.

**Comment by ghidalgo3** [comment]
There will be a brief service interruption within the next 30 minutes, should not last longer than 5 minutes.

**Comment by ghidalgo3** [comment]
The maintenance work is now complete. Sorry for the interruptions!
