### ISSUE TITLE
change in the NDVI value when compared to sentinel hub

### ISSUE THREAD

**Issue by krishnaglodha** [microsoft/PlanetaryComputer#349]
Hi, I'm trying to create NDVI based on `sentinel-2-l2a` , bit I see difference in values on pixels when compared with sentinel hub 

Here is the image from sentinel hub 
<img width="994" alt="Screenshot 2024-05-23 at 3 29 33 PM" src="https://github.com/microsoft/PlanetaryComputer/assets/47075664/b7db3d77-1429-4625-8043-ba4c56e3b0bb">

we can see that it ranges from 18 to 61 i.e.  0.07 to 0.23 ( divided by 255 ) 

and here is the image from planetary
<img width="1072" alt="Screenshot 2024-05-23 at 3 28 02 PM" src="https://github.com/microsoft/PlanetaryComputer/assets/47075664/cad8e0ae-ef27-4680-9d88-dfc068e2e077">

where values are ranging between 0.04 to 0.15

my code looks like 
```
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)
time_range = f"{start_date}/{end_date}"
collection = "sentinel-2-l2a"
geometry = polygon["features"][0]["geometry"]
search = catalog.search(
    collections=[collection], intersects=geometry, datetime=time_range
)  # bbox=tas_bbox   
print(search.get_all_items())
data = load(
            search.items(),
            geopolygon=geometry,
            chunks={},
            resolution=1,
            projection="epsg:3857",
        ).isel(time=0)
dc = data.rio.clip([geometry], crs="epsg:4326")
index_xarray = ms.ndvi(dc.B08, dc.B04)
index_xarray.rio.to_raster("planet_scope.tif")
```

**Comment by TomAugspurger** [comment]
.Looks like a few variables in your snippet aren't defined, so I can't reproduce it (start_date, end_date, ms)

Do you know offhand whether the values from Sentinel Hub are L1C or L2A, and which processing baseline it's using? It might be better to compare just the raw values (from before the NDVI calculation).

**Comment by krishnaglodha** [comment]
here are the variables
```
polygon = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              79.06776796168413,
              19.043044385618458
            ],
            [
              79.06776796168413,
              19.041761558038218
            ],
            [
              79.06973122024931,
              19.041761558038218
            ],
            [
              79.06973122024931,
              19.043044385618458
            ],
            [
              79.06776796168413,
              19.043044385618458
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}

start_date = '2024-01-01'
end_date = '2024-01-06'
```

**Comment by krishnaglodha** [comment]
PS: I also tested out result in comparison with agromonitoring.com , and got similar differences
<img width="339" alt="Screenshot 2024-05-24 at 9 43 56 AM" src="https://github.com/microsoft/PlanetaryComputer/assets/47075664/fedde65a-4647-445f-97d5-bad1c629a757">

vs microsoft
<img width="375" alt="Screenshot 2024-05-24 at 9 44 06 AM" src="https://github.com/microsoft/PlanetaryComputer/assets/47075664/1503ce4a-d278-4864-9364-bcf6ac34822b">

**Comment by krishnaglodha** [comment]
> .Looks like a few variables in your snippet aren't defined, so I can't reproduce it (start_date, end_date, ms)
> 
> Do you know offhand whether the values from Sentinel Hub are L1C or L2A, and which processing baseline it's using? It might be better to compare just the raw values (from before the NDVI calculation).

when we download raw data from `pc` the range is between thousands, whereas sentinel-hub data range is betweek 0-255, what might be going wrong ?

**Comment by TomAugspurger** [comment]
> when we download raw data from pc the range is between thousands, whereas sentinel-hub data range is betweek 0-255, what might be going wrong ?

That might be to the baseline or units I mentioned in https://github.com/microsoft/PlanetaryComputer/issues/350#issuecomment-2127350480.

**Comment by krishnaglodha** [comment]
> > when we download raw data from pc the range is between thousands, whereas sentinel-hub data range is betweek 0-255, what might be going wrong ?
> 
> That might be to the baseline or units I mentioned in [#350 (comment)](https://github.com/microsoft/PlanetaryComputer/issues/350#issuecomment-2127350480).

how do we use this units ?

**Comment by krishnaglodha** [comment]
I tried replicating same results with `'https://earth-search.aws.element84.com/v1'` and surprisingly I got correct result ( similar to sentinel hub ) with earth search STAC link.

**Comment by TomAugspurger** [comment]
> how do we use this units ?

Sorry, I don't understand the question.

I'm not an expert, but my understanding is that bands like "B04" are provided as "digital numbers" and are typically in the range 0-4000.

**Comment by krishnaglodha** [comment]
> I tried replicating same results with `'https://earth-search.aws.element84.com/v1'` and surprisingly I got correct result ( similar to sentinel hub ) with earth search STAC link.

@TomAugspurger , what is your comment on this ?

**Comment by TomAugspurger** [comment]
I’m not sure, I haven’t used that data before.
________________________________

**Comment by 11904212** [comment]
> I tried replicating same results with `'https://earth-search.aws.element84.com/v1'` and surprisingly I got correct result ( similar to sentinel hub ) with earth search STAC link.

They seem to apply the offset to there COG assets. I ran into a similar problem and documented it. [here](https://github.com/11904212/element84-sentinel2-dataset)

the confusing part is that they use the [STAC raster extension](https://github.com/stac-extensions/raster) to provide the values for offset and scale. 
```
"raster:bands": [
    {
        "nodata": 0,
        "data_type": "uint16",
        "bits_per_sample": 15,
        "spatial_resolution": 10,
        "scale": 0.0001,
        "offset": -0.1
    }
```
However the offset is still "-0.1". IMHO it should be "0" since the values are already [harmonized](https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l2a/#harmonize-values). but this is another story....


the deviations you have observed can also be caused by the other [DEM used by PC](https://github.com/microsoft/PlanetaryComputer/discussions/149)

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
