### ISSUE TITLE
Error signing S2 images

### ISSUE THREAD

**Issue by whj-stanford** [microsoft/PlanetaryComputer#356]
Was trying to run this [MOSAIKS tutorial example ](https://github.com/microsoft/PlanetaryComputerExamples/blob/main/tutorials/mosaiks.ipynb)from my computer, and encountered 

OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt 

when executing the In[13]:

df3 = df2.dropna(subset=["stac_item"])

matching_urls = [
    pc.sign(item["assets"]["visual"]["href"]) for item in df3.stac_item.tolist()
]

points = df3[["lon", "lat"]].to_numpy()
population_log = np.log10(df3["population"].to_numpy() + 1)

I installed all the necessary packages. Any ideas? Thanks in advance!

**Comment by TomAugspurger** [comment]
Sounds like an issue with your Python (or requests?) installation not being configured properly. I'm not sure why that would be.

**Comment by mmcfarland** [comment]
I'm not sure what your OS is, but if it's Debian based, you could try `sudo apt install ca-certificates` or the equivalent for your OS.

**Comment by whj-stanford** [comment]
Thanks for the helpful comments @TomAugspurger @mmcfarland ! I am running on my mac and maybe there is something missing in my env. 

I resolved the problem by downloading the missing _ca-certificates.crt_ file from the Github codespace using the Planetary Computer environment. Everything runs smoothly now. Hope this could be helpful for others who has similar issues.
