### ISSUE TITLE
Error in Chloris Biomass Data Notebook

### ISSUE THREAD

**Issue by mattsmiScientific** [microsoft/PlanetaryComputer#36]
Just noting an error with the Chloris biomass data notebook: chloris-biomass-example.ipynb

The image shown at the bottom obviously has errors (biomass numbers are not what they should be)

I think the error is made in the second-last code block.

nodata should be filtered out / treated as nodata BEFORE the grid is downsampled. Failure to do this means that cells with real values surrounding nodata get contaminated with nodata values. Specific code block:

"""

%%time
factor = 10
coarse_biomass = (
    ds.biomass.coarsen(dim={"x": factor, "y": factor}, boundary="trim").mean().compute()
)

# Filter out nodata
coarse_biomass = coarse_biomass.where(coarse_biomass < ds.attrs["_FillValue"])
coarse_biomass.shape

"""

**Comment by mattsmiScientific** [comment]
I managed to fix this by doing

# Filter out nodata
ds_masked = ds.where(ds['biomass'] != ds.attrs["_FillValue"]) 

%%time
factor = 10
coarse_biomass = (
    ds_masked.biomass.coarsen(dim={"x": factor, "y": factor}, boundary="trim").mean().compute()
)

coarse_biomass.shape

**Comment by TomAugspurger** [comment]
Thanks for catching that! I've fixed it in https://github.com/microsoft/PlanetaryComputerExamples/pull/130 by using the `masked=True` keyword when reading the data.
