### ISSUE TITLE
Items paging links broken

### ISSUE THREAD

**Issue by captaincoordinates** [microsoft/PlanetaryComputer#360]
At some point today items paging links appear to have been broken. It was working fine for me several hours ago, but now [this sentinel-2-l2a items link](https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items) returns the following `links` array (note the missing `/api/stac/v1` in the "next" link):

```JSON
[
    {
      "rel": "collection",
      "type": "application/json",
      "href": "https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a"
    },
    {
      "rel": "parent",
      "type": "application/json",
      "href": "https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a"
    },
    {
      "rel": "root",
      "type": "application/json",
      "href": "https://planetarycomputer.microsoft.com/api/stac/v1/"
    },
    {
      "rel": "self",
      "type": "application/geo+json",
      "href": "https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items"
    },
    {
      "rel": "next",
      "type": "application/geo+json",
      "method": "GET",
      "href": "https://planetarycomputer.microsoft.com/collections/sentinel-2-l2a/items?token=next:sentinel-2-l2a:S2B_MSIL2A_20240613T142719_R053_T21QYB_20240613T180205"
    }
  ]
```

**Comment by TomAugspurger** [comment]
Thanks for the report. We'll take a look.

**Comment by TomAugspurger** [comment]
This is going to take a longer to fix than expected. It's not ideal, but in the meantime, you might try manually patching the `next` link to include the `api/stac/v1/` prefix :/

**Comment by mmcfarland** [comment]
This should be resolved now, the `next` link includes the full expected URL path. Thanks for the reproducible example 👍
