### ISSUE TITLE
ODC-stac can't access Landsat-5 image piexl data

### ISSUE THREAD

**Issue by 765302995** [microsoft/PlanetaryComputer#365]
code:
for i in landsat_5(this is a collecion):
        data = odc.stac.stac_load(
        [i], bands=bands_of_interest, bbox=bbox_of_interest
    ).isel(time=0)

output information:

L5 processing:  93%|█████████▎| 644/690 [04:09<00:05,  8.69it/s]Aborting load due to failure while reading: https://landsateuwest.blob.core.windows.net/landsat-c2/level-2/standard/tm/1985/053/014/LT05_L2SP_053014_19850909_20200918_02_T1/LT05_L2SP_053014_19850909_20200918_02_T1_SR_B4.TIF?st=2024-06-25T05%3A28%3A37Z&se=2024-06-26T06%3A13%3A37Z&sp=rl&sv=2024-05-04&sr=c&skoid=9c8ff44a-6a2c-4dfb-b298-1c9212f64d9a&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2024-06-26T05%3A24%3A50Z&ske=2024-07-03T05%3A24%3A50Z&sks=b&skv=2024-05-04&sig=7HkxwNKSHv8vB5qnbvf9f5YqoQ/2aEziYGztk%2BSikVU%3D:1

L5 processing:  94%|█████████▎| 646/690 [04:09<00:05,  8.79it/s]Aborting load due to failure while reading: https://landsateuwest.blob.core.windows.net/landsat-c2/level-2/standard/tm/1985/053/014/LT05_L2SP_053014_19850824_20200918_02_T1/LT05_L2SP_053014_19850824_20200918_02_T1_SR_B4.TIF?st=2024-06-25T05%3A28%3A37Z&se=2024-06-26T06%3A13%3A37Z&sp=rl&sv=2024-05-04&sr=c&skoid=9c8ff44a-6a2c-4dfb-b298-1c9212f64d9a&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2024-06-26T05%3A24%3A50Z&ske=2024-07-03T05%3A24%3A50Z&sks=b&skv=2024-05-04&sig=7HkxwNKSHv8vB5qnbvf9f5YqoQ/2aEziYGztk%2BSikVU%3D:1
Aborting load due to failure while reading: https://landsateuwest.blob.core.windows.net/landsat-c2/level-2/standard/tm/1985/053/014/LT05_L2SP_053014_19850808_20200918_02_T1/LT05_L2SP_053014_19850808_20200918_02_T1_SR_B4.TIF?st=2024-06-25T05%3A28%3A37Z&se=2024-06-26T06%3A13%3A37Z&sp=rl&sv=2024-05-04&sr=c&skoid=9c8ff44a-6a2c-4dfb-b298-1c9212f64d9a&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2024-06-26T05%3A24%3A50Z&ske=2024-07-03T05%3A24%3A50Z&sks=b&skv=2024-05-04&sig=7HkxwNKSHv8vB5qnbvf9f5YqoQ/2aEziYGztk%2BSikVU%3D:1

**Comment by TomAugspurger** [comment]
Thanks for opening this issue. A few questions:

1. Can you show a full reproducible example?
2. Are you able to load just those assets by themselves?
3. Is this reproducible, or was that a temporary networking issue?

**Comment by 765302995** [comment]
1.Yes, this is an example:
import pandas as pd
import numpy as np
from tqdm import tqdm
import pystac_client
import planetary_computer
import odc.stac
# import matplotlib.pyplot as plt
from pystac.extensions.eo import EOExtension as eo
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)
bbox_of_interest = [  -84.751904,39.571318 ,   -84.746904,   39.576318]
time_of_interest = "1982-01-01/2022-12-21"
data_value_L5 = pd.DataFrame(columns=['time', 'blue', 'green','red', 'nir08', 'swir16', 'swir22', "lwir11"  ])
for i in items_L5:
    bands_of_interest = ["nir08", "red", "green", "blue", "swir16","swir22", "lwir11"  ]
    data = odc.stac.stac_load(
        [i], bands=bands_of_interest, bbox=bbox_of_interest
    ).isel(time=0)
2.  yes, I can single load those assets by themselves.
3.  is a  reproducible, you can try above example code.

**Comment by 777arc** [comment]
Looks like there are several different things going on here based on the errors/traceback.  For starters, there's at least one bad asset, `LC08_L2SP_020032_20221026_02_T2` is giving me error `rasterio._err.CPLE_AppDefinedError: TIFFFillTile:Read error at row 4294967295, col 4294967295, tile 788; got 0 bytes, expected 91677`, might have been corrupt from our data source.  

Then several others (eg LE07_L2SP_020033_20220712_02_T1) don't have lwir11 so you'll need to remove it from the bands of interest for those. 

Lastly, LC09_L2SP_020032_20220425_02_T2 is giving a `rasterio.errors.RasterioIOError` `not recognized as being in a supported file format`.

Here's what I used.  About 90% of the items are working fine though.  

```
import pandas as pd
import pystac_client
import planetary_computer
import odc.stac
from matplotlib import pyplot as plt
import traceback
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)
bbox_of_interest = [  -84.751904,39.571318 ,   -84.746904,   39.576318]
time_of_interest = "1982-01-01/2022-12-21"
data_value_L5 = pd.DataFrame(columns=['time', 'blue', 'green','red', 'nir08', 'swir16', 'swir22', "lwir11"  ])
items_L5 = catalog.search(
    collections=["landsat-c2-l2"],
    bbox=bbox_of_interest,
    datetime=time_of_interest,
).item_collection()
print("found", len(items_L5), "items")
bands_of_interest = ["nir08", "red", "green", "blue", "swir16", "swir22", "lwir11"]
for i in items_L5:
    print(i.id)
    try:
        data = odc.stac.stac_load([i], bands=bands_of_interest, bbox=bbox_of_interest).isel(time=0)
    except Exception as e:
        print(e)
        print("======traceback=======")
        print(traceback.format_exc())
        print("======================\n")
        continue
```

**Comment by 765302995** [comment]
> Looks like there are several different things going on here based on the errors/traceback. For starters, there's at least one bad asset, `LC08_L2SP_020032_20221026_02_T2` is giving me error `rasterio._err.CPLE_AppDefinedError: TIFFFillTile:Read error at row 4294967295, col 4294967295, tile 788; got 0 bytes, expected 91677`, might have been corrupt from our data source.
> 
> Then several others (eg `LE07_L2SP_020033_20220712_02_T1`) don't have `lwir11` so you'll need to remove it from the bands of interest for those.
> 
> Lastly, `LC09_L2SP_020032_20220425_02_T2` is giving a `rasterio.errors.RasterioIOError` `not recognized as being in a supported file format`, not sure why.
> 
> Here's what I used. If you leave out `lwir11` you should be able to process almost all of the items.
> 
> ```
> import pandas as pd
> import pystac_client
> import planetary_computer
> import odc.stac
> from matplotlib import pyplot as plt
> import traceback
> catalog = pystac_client.Client.open(
>     "https://planetarycomputer.microsoft.com/api/stac/v1",
>     modifier=planetary_computer.sign_inplace,
> )
> bbox_of_interest = [  -84.751904,39.571318 ,   -84.746904,   39.576318]
> time_of_interest = "1982-01-01/2022-12-21"
> data_value_L5 = pd.DataFrame(columns=['time', 'blue', 'green','red', 'nir08', 'swir16', 'swir22', "lwir11"  ])
> items_L5 = catalog.search(
>     collections=["landsat-c2-l2"],
>     bbox=bbox_of_interest,
>     datetime=time_of_interest,
> ).item_collection()
> print("found", len(items_L5), "items")
> bands_of_interest = ["nir08", "red", "green", "blue", "swir16", "swir22", "lwir11"]
> for i in items_L5:
>     print(i.id)
>     try:
>         data = odc.stac.stac_load([i], bands=bands_of_interest, bbox=bbox_of_interest).isel(time=0)
>     except Exception as e:
>         print(e)
>         print("======traceback=======")
>         print(traceback.format_exc())
>         print("======================\n")
>         continue
> ```

thanks a lot, I want lwir11 to get LST, How to get all this information?  if ROI get 0  bytes Landsat 5/7/8/9, how to ignore this data and get next data.

**Comment by 777arc** [comment]
Well the try/except block in my example can be used to ignore and move on to the next item, you just have to do something with the data or store it somewhere before moving on to the next item.  When you say "How to get all this information" what exactly are you referring to?

**Comment by 765302995** [comment]
> Well the try/except block in my example can be used to ignore and move on to the next item, you just have to do something with the data or store it somewhere before moving on to the next item. When you say "How to get all this information" what exactly are you referring to?

Well,  I can use try/except to moving on to the next time. thanks a lot.
