### ISSUE TITLE
Migrant from other geo platform: what is possible on MPC?

### ISSUE THREAD

**Issue by suredream** [microsoft/PlanetaryComputer#375]
hi MPC team:

First of all, thank you for your hard work in creating such an outstanding product!

Previously, I was a user of the hub, where I explored some examples, but I didn’t get the opportunity to dive deeper with a real-world problem. Lately, after facing some frustrations with other platforms, I'm eager to better understand what MPC has to offer now.

E.g., I came across information stating that the STAC API is "anonymous but throttled." Could you clarify what that means? If I wanted to conduct **nationwide mapping across the CONUS region using Sentinel-2 data**, would that still be feasible or easy to do, or would I be limited to processing just a few tiles? Or foresee long time to finish? Or I can still do it but pay the expense?

I also used to utilize the DASK gateway on MPC, which was a fantastic feature! Now, without access to the hub, is there another way I can perform large-scale parallel data computing on MPC? What challenges should I expect?

Many thanks,

**Comment by ghidalgo3** [comment]
Hi @suredream, thanks for your interest in Planetary Computer!

> Could you clarify what that means?

You are unlikely to run into our throttling limits as long as you:
1. Query for items within a specific collection (do not query for items across all collections)
2. Run your process within the West Europe Azure Region.
We do not publish the limits, but they are very generous.

> If I wanted to conduct nationwide mapping across the CONUS region using Sentinel-2 data, would that still be feasible or easy to do, or would I be limited to processing just a few tiles? 

It is feasible, but again please consider running your process in the West Europe Azure datacenter for the best performance and scale.

>  Or foresee long time to finish?

It depends on what you are doing, Sentinel-2 is a very large collection. You probably do not want copy the sentinel2 assets yourself, instead access them through our SAS API.

> Or I can still do it but pay the expense?

Planetary Computer is free, we do not offer a paid tier.

> Now, without access to the hub, is there another way I can perform large-scale parallel data computing on MPC? 

You could create your own Dask cluster in West Europe, or use a solution like https://www.coiled.io/ . 

> What challenges should I expect?

Too much data :)

**Comment by 777arc** [comment]
Closing, feel free to reopen if you run into any more questions
