### ISSUE TITLE
S2 obtains NDVI time series curve

### ISSUE THREAD

**Issue by Mrjoecen** [microsoft/PlanetaryComputer#386]
Excuse me, how can I obtain NDVI time series curves for a certain period of time within the AOI area? Is there a similar document? I don't seem to be able to find it. #

**Comment by 777arc** [comment]
Did you try this tutorial yet? https://github.com/microsoft/PlanetaryComputerExamples/blob/main/tutorials/ndvi_hotspots.ipynb

**Comment by Mrjoecen** [comment]
Okay, thank you. Let me take a look

**Comment by 777arc** [comment]
Closing, feel free to re-open if you need more info!
