### ISSUE TITLE
please replace all instances of BDP to NODD

### ISSUE THREAD

**Issue by Patrick-Keown** [microsoft/PlanetaryComputer#398]
please replace all instances of BDP to NODD

**Comment by 777arc** [comment]
Done, eg https://planetarycomputer.microsoft.com/dataset/storage/noaa-hrrr let us know if you spot any others, but I believe I got them all

for reference https://github.com/microsoft/AIforEarthDataSets/commit/53dcda0b25a8988263ced7ac96b0ca50d287b1ea

**Comment by Patrick-Keown** [comment]
Thanks!


Patrick Keown

Program Manager, NOAA Open Data Dissemination (NODD)

Office of the Chief Information Officer (OCIO)

National Oceanic & Atmospheric Administration

(615) 319-5906 | ***@***.***

"Be sure when you step, step with care and great tact" - Dr. Seuss


Schedule a Meeting with Me! <https://calendar.app.google/BWJGjd9f9JRLRzwC9>
