### ISSUE TITLE
Spawn failed: Server Error

### ISSUE THREAD

**Issue by orttak** [microsoft/PlanetaryComputer#51]
Hi

How can I solve this problem?

Thanks
![image](https://user-images.githubusercontent.com/28723856/165307067-874f411e-7e9b-423b-8963-15d5729d41d7.png)

**Comment by TomAugspurger** [comment]
Looks like your home directory was full, so the pod wasn't able to start. I've bumped its size slightly. We recommend only storing code / notebooks / small outputs in your home directory, and writing large outputs to blob storage: https://planetarycomputer.microsoft.com/docs/overview/environment/#understanding-the-file-system.

Let me know if you're still running into issues.
