### ISSUE TITLE
Spawn failed: Timeout

### ISSUE THREAD

**Issue by harish5p** [microsoft/PlanetaryComputer#55]
![Screenshot 2022-05-07 at 04-12-08 Hub Planetary Computer](https://user-images.githubusercontent.com/20576094/167224964-b213a75e-8946-43b8-aa36-dfce39728636.png)

It looks like I'm facing the same issue as another user [here](https://github.com/microsoft/PlanetaryComputer/issues/51), I'll delete files if I can login which I'm unable to do.

**Comment by harish5p** [comment]
Update: It's working now

**Comment by TomAugspurger** [comment]
Just to note: you might see that "Spawn Failed: timeout" error for multiple reasons. In this case, it looks like our quota of GPUs was all filled up.
