### ISSUE TITLE
Request pysptools package to be installed in the default environment 

### ISSUE THREAD

**Issue by xjtang** [microsoft/PlanetaryComputer#56]
The "Abundance Maps" tool in this package is very useful in image processing

**Comment by TomAugspurger** [comment]
Looks like it's not in conda-forge yet: https://github.com/conda-forge/staged-recipes/issues/5575?msclkid=cb8c3bbbcf8d11eca601cd07cb4120aa. We'd need to confirm that none of its dependencies conflict with what's already present.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
