### ISSUE TITLE
Update stackstac to the latest version

### ISSUE THREAD

**Issue by xjtang** [microsoft/PlanetaryComputer#61]
Would it be possible to update stackstac to the latest version (0.4.1)?

**Comment by TomAugspurger** [comment]
The latest container images have it: https://github.com/microsoft/planetary-computer-containers/blob/535748775b971f2fe406c99a1714dd3d663f1db8/python/conda-linux-64.lock#L550. We'll roll those out to the Hub in the next couple days, after doing some integration testing.

**Comment by TomAugspurger** [comment]
The Hub now includes stackstac 0.4.1.
