### ISSUE TITLE
Landsat 8 Collection 2 notebook example 404

### ISSUE THREAD

**Issue by hectorpatino** [microsoft/PlanetaryComputer#64]
I was checking the [documentation](https://planetarycomputer.microsoft.com/docs/overview/about) and I realise that the Landsat8 Collection 2 link is not found.

**Comment by TomAugspurger** [comment]
Thanks for the report! This will be fixed by https://github.com/microsoft/PlanetaryComputerDataCatalog/pull/315.

In the meantime, https://planetarycomputer.microsoft.com/dataset/landsat-c2-l2#Example-Notebook is the link you want.

**Comment by TomAugspurger** [comment]
That's merged now. The link will be fixed when we redeploy the documentation later today. Thanks again!
