### ISSUE TITLE
Collections endpoint on prod points to staging

### ISSUE THREAD

**Issue by rowanwins** [microsoft/PlanetaryComputer#65]
Hey there PlanetaryComputer team,

I just noticed that when you visit the [production STAC collections endpoint](https://planetarycomputer.microsoft.com/api/stac/v1/collections) the individual collection feature `links` `href`'s point to the staging environment, eg
````
{

   id: "io-lulc",
   links: [{
       href: "https://planetarycomputer-staging.microsoft.com/api/stac/v1/collections/io-lulc/items"
       rel: "items"
      type: "application/geo+json"
   }]
}
````

 I'm guessing something has gone a little astray :)

Cheers
Rowan

**Comment by TomAugspurger** [comment]
Thanks for the report! We'll look into it.

In the meantime, planetarycomputer.microsoft.com and planetarycomputer-staging.microsoft.com are pointing to the exact same thing, so the data and APIs are totally safe to use until we get this sorted out.

**Comment by TomAugspurger** [comment]
This should be fixing itself over the next little while.

For background, [our APIs](https://github.com/microsoft/planetary-computer-apis) are now caching requests to some endpoints. The cache key didn't include whether or not the request hostname came from production or staging (which are currently pointing to the same API instances) so a request to planetarycomputer.microsoft.com might return a cached request from planetarycomputer-staging.microsoft.com.

We've redirected `-staging` away from the production API instances and will update the caching logic to include the hostname so this doesn't happen in the future.

Thanks again for catching and reporting this!

**Comment by rowanwins** [comment]
Thanks @TomAugspurger for the explanation!
