### ISSUE TITLE
Searching and the anti-meridian

### ISSUE THREAD

**Issue by rowanwins** [microsoft/PlanetaryComputer#71]
I've noticed some quirky behaviour when using a bbox search that sometimes the results include items which cross the anti-meridian.

For example this I was searching for items in the middle of Australia using a query like
`https://planetarycomputer.microsoft.com/api/stac/v1/search?collections=landsat-8-c2-l2&bbox=129.885371,-29.068322,137.230638,-23.538097&ids=LC08_L2SR_072076_20211222_02_T2`
Note I've included the item id in the above query just so it's obvious :)

The results include this item.
https://planetarycomputer.microsoft.com/api/stac/v1/collections/landsat-8-c2-l2/items/LC08_L2SR_072076_20211222_02_T2
The item has a geometry which  travels from `179.2700366` to `-178.1091546` and so it wraps around the world.

Ah the joys of dealing with the anti-meridian :)

Cheers
Rowan

**Comment by rowanwins** [comment]
Thanks for the info @TomAugspurger , happy to close or leave open until the issue is more widely resolved across collections

**Comment by TomAugspurger** [comment]
We've deprecated the `landsat-8-c2-l2` collection and aren't planning to update those existing items, so I'll close this. But let me know if you do spot similar issues with other collections.

**Comment by rowanwins** [comment]
Just one final note that there is a [STAC extension](https://github.com/stac-extensions/version) for flagging collections as deprecated so that might be worth looking into.

**Comment by TomAugspurger** [comment]
Yep, thanks. We're working out our versioning strategy right now.
