### ISSUE TITLE
Trouble installing geowombat package

### ISSUE THREAD

**Issue by MatthewPierson90** [microsoft/PlanetaryComputer#73]
Hello,

I am attempting to install the geowombat package (https://github.com/jgrss/geowombat) on the planetary computer hub. The issue has to do with C compilers not being able to find libraries. 

Attempting to install geowombat with no changes I get the following error

`  /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/srv/conda/envs/notebook/lib -Wl,-rpath-link,/srv/conda/envs/notebook/lib -L/srv/conda/envs/notebook/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/srv/conda/envs/notebook/lib -Wl,-rpath-link,/srv/conda/envs/notebook/lib -L/srv/conda/envs/notebook/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/srv/conda/envs/notebook/lib -Wl,-rpath-link,/srv/conda/envs/notebook/lib -L/srv/conda/envs/notebook/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include build/temp.linux-x86_64-cpython-38/src/geowombat/moving/_moving.o -o build/lib.linux-x86_64-cpython-38/geowombat/moving/_moving.cpython-38-x86_64-linux-gnu.so -fopenmp
  /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgcc
  /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lgcc
  collect2: error: ld returned 1 exit status`

If try `find /srv -name "*lgcc*"` nothing is returned (similarly for `find /usr -name "*lgcc*"`.)

I have tried to install various packages from conda, `mamba install -c conda-forge compilers` and `mamba install -c conda-forge gxx_linux-64`, both of which result in similar missing library errors. For compilers I get 

`  /srv/conda/envs/notebook/bin/x86_64-conda-linux-gnu-cc -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/srv/conda/envs/notebook/lib -Wl,-rpath-link,/srv/conda/envs/notebook/lib -L/srv/conda/envs/notebook/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/srv/conda/envs/notebook/lib -Wl,-rpath-link,/srv/conda/envs/notebook/lib -L/srv/conda/envs/notebook/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/srv/conda/envs/notebook/lib -Wl,-rpath-link,/srv/conda/envs/notebook/lib -L/srv/conda/envs/notebook/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /srv/conda/envs/notebook/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /srv/conda/envs/notebook/include build/temp.linux-x86_64-cpython-38/src/geowombat/moving/_moving.o -o build/lib.linux-x86_64-cpython-38/geowombat/moving/_moving.cpython-38-x86_64-linux-gnu.so -fopenmp
  /srv/conda/envs/notebook/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find /usr/lib64/libpthread_nonshared.a
  collect2: error: ld returned 1 exit status`

Thanks!

**Comment by TomAugspurger** [comment]
Hmm there's no C compiler in the default image, and I don't think we'd want to include one just for size.

I know that conda's compilers can be a bit tricky to use outside of `conda-build`.

The best path forward might be a conda-forge recipe for geowombat.

**Comment by ritviksahajpal** [comment]
Looks like they recently released a conda-forge recipe for geowombat `https://anaconda.org/conda-forge/geowombat`

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
