### ISSUE TITLE
Sometimes cluster.scale(n) doesn't get n workers

### ISSUE THREAD

**Issue by MikeBeller** [microsoft/PlanetaryComputer#8]
Hi.  Apologies in advance if this is not the right place for this issue.
If I acquire a cluster as follows:

```
cluster = dask_gateway.GatewayCluster()
client = cluster.get_client()
cluster.scale(16)
```

Typically, looking in the cluster dashboard, I see fewer than 16 workers.  Today when I was working, I typically saw 6 or maybe 10. How does the dask_gateway decide how many resources I get?  Is there a reason I'm not getting my 16 workers?

Note I am not talking about large n.  Haven't even tried more than maybe n=32.

**Comment by TomAugspurger** [comment]
This is a perfect place to report this type of issue.

> How does the dask_gateway decide how many resources I get?

There a few stages:

1. `GatewayCluster()` has to make a scheduler pod, which typically fits somewhere on the cluster and so completes pretty quickly.
2. `cluster.scale(n)` needs to make `n` worker pods.

Sometimes, there will be empty spots on the cluster and workers will show up in a second or two. If there isn't any free space, workers will take some time to come online. We need to start a brand new VM (which takes a few minutes, sometimes longer) and we need to download the environment image (which can take another few minutes).

Unfortunately, you as a user don't have *any* visibility into what's going on during `.scale` other than how many workers are ready.

If your analysis relies on having some number of workers ready up front (e.g. you start by loading a bunch of data) then you can use `client.wait_for_workers` to wait for n workers:

```python
cluster.scale(16)
%time client.wait_for_workers(16)
```

I would expect that to complete in a few seconds if there's room on the cluster, and perhaps 5-8 minutes if there's not room and new VMs need to be started.

**Comment by MikeBeller** [comment]
Thanks Tom.  That's super helpful!  

On a related note: I have noticed that when I am using dynamic scaling, sometimes computations just crap out with a Python error that has nothing to do with my code (as far as I can tell).  If I can isolate a repeatable case I will post it as a separate issue.
