### ISSUE TITLE
Add 'servers' field to the API definition document

### ISSUE THREAD

**Issue by ghobona** [microsoft/PlanetaryComputer#84]
OpenAPI allows for the use of a `servers` field for providing information about connectivity to a target server.

https://spec.openapis.org/oas/v3.0.3#openapi-object

The field is very useful in a variety of use cases.

Please add a `servers` field in the OpenAPI document.

I presume it would be something like:

```json
    "servers": [
        {
            "description": "Microsoft Planetary Computer STAC API",
            "url": "https://planetarycomputer.microsoft.com/api/stac/v1"
        }
    ]
```

**Comment by TomAugspurger** [comment]
Thanks for opening this issue. Just for my own curiosity, can share a bit more about why that field might be useful?

cc @mmcfarland.

**Comment by ghidalgo3** [comment]
`Closed` due to inactivity, feel free to reopen if you would like to continue this discussion.
